### ISSUE TITLE
Ensure all HCA publications are entered into the Spreadsheet tracker

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-wrangler-central#10]
**Description of the task:**

As data wranglers we need to ensure all HCA publications make it into the DCP. The best way we have to ensure this is to enter them into the spreadsheet tracker where we can assess their prioritisation, suitability and any blocking factors.

The spreadsheet tracker is here: https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/edit#gid=0

Updated list of HCA publications: https://docs.google.com/document/d/1yx2W6OFovJ8bHlnM-Gczmshaet5N5hcSBcP9u438a9g/edit#heading=h.e2hmauyqmsar - this is not a living document 

@zperova has done some work on assessing these publications so please leave the link to any documents/sheets you have here

**Acceptance criteria for the task:**

- [x] all publications from HCA publication list have been assessed (@zperova)
- [x] all publications from the Biorxiv HCA channel list have been assessed (@zperova )
- [x] all HCA publications are in the spreadsheet tracker (@zperova)
- [x] appropriate columns filled out to assess the publication's suitability

**Comment by mshadbolt** [comment]
@zperova will add all publications to the spreadsheet and will mark obvious ones that aren't suitable.

Other wranglers will need to do a full assessment of the suitability of other publications

**Comment by zperova** [comment]
Tim Tickle is working on the DCP2.0 Metrics assessing the HCA publication list. I will be adding to his spreadsheet for now until this is unblocked. The HCA publication list for Metrics is here:
https://docs.google.com/spreadsheets/d/1WjKdy5YKG0SYQ3zIUPHebVhOsBkTA23iPEOGq0pRvJs/edit#gid=0

**Comment by zperova** [comment]
The HCA publication list on the humancellatlas website: https://www.humancellatlas.org/publications/ and the HCA channel in Biorxiv: http://connect.biorxiv.org/relate/content/163?page=1 do not have the same papers. 
Contacted Tracey to clarify, as well as to clarify what happens when an HCA approved pre-print is published in a peer-reviewed journal.

**Comment by zperova** [comment]
Marked everything we have in the DCP1.0 in Tim's spreadsheet.

**Comment by zperova** [comment]
HCA Publications from humancellatlas.org added to the Dataset Tracker

**Comment by mshadbolt** [comment]
@zperova are you able to explain the changes you made to the publications columns?

I find it kind of confusing to have four different columns where I could find a publication

**Comment by zperova** [comment]
Linking assessment of the current biorxiv HCA channel (as some inconsistencies with the HCA publication list): https://docs.google.com/document/d/18JElZI0IClVxG4ThhzSbaxY6-awua1yI9Vdz6JqBn7k/edit

**Comment by zperova** [comment]
@mshadbolt it is currently confusing. I added the following tabs:
Associated humancellatlas.org Publication - this is publication that has been approved as a HCA publication by the HCA Publications committee and the one that is listed on the website
Associated HCA Biorxiv channel publication if different - this is a publication that is lister in the HCA channel on Biorxiv, it is different only in couple of instances, so this column can be removed once the inconsistencies have been resolved. Tracey has been emailed about this. 
Other publication on this dataset - this column has publications which are also associated with the dataset, such as peer-reviewd article that came after the pre-print has been accepted as HCA publication.  This needs to be reconsiled with the original Publication column - is the original Publication column has the ones that are in the HCA metadata for thos datasets that are in the DCP? If the publication is mentioned there, is it in the HCA metadata for the DCP datasets or it needs to be added. I have not thought through what is the best way to capture these differences in the Spreadsheet and will be happy to hear suggestions. Taggin @ami-day as she is working on the improvement for the spreadsheet. Ultimately we would like to track this to avoid duplication of work.

**Comment by zperova** [comment]
This is now done as described in the ticket body. If there is anything else needed for this ticket please let me know. @lauraclarke 
@mshadbolt not sure why it is blocked by KR1?

**Comment by mshadbolt** [comment]
I think I put that as I was thinking we needed to assess what was in the list before proceeding but have now removed it

**Comment by lauraclarke** [comment]
Looks good to me, brief but descriptive and nice to tag the community list membership in each.

This does mean we will need to be more aware of spam and spam members on the list as it becomes more broadly advertised but I don't think the risk is massive given the google form

**Comment by zperova** [comment]
@lauraclarke reading the above comment makes me think it was intended for a different ticket.

**Comment by lauraclarke** [comment]
You are right, that was for the HCA metadata community videos, too many different github issues open
