### ISSUE TITLE
Re-export all datasets stuck in exporting

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#1082]
**Description of the task:**

Now that the fixes have been deployed, exporting should be back to a normal operational state

All the datasets that have gotten stuck in the past few weeks need to be re-exported

**Datasets**

Enrique

- [THP1StimulationCells](https://contribute.data.humancellatlas.org/submissions/detail?uuid=4f40bcbf-6c56-422c-ac8a-3f162f818595)
	- [x] Graph valid
	- [x] Exporting
	- [x] Exported
        - [x] Import Form Sent
- [SingleCelleQTLCoexpressionAnalysis](https://contribute.data.humancellatlas.org/submissions/detail?uuid=378455be-3938-4713-abfa-7584e1f63942)
	- [x] Graph valid
	- [x] Exporting
	- [x] Exported
        - [x] Import Form Sent
- [HematopoieticImmuneCellAtlas](https://contribute.data.humancellatlas.org/submissions/detail?uuid=28ff3c1c-08e9-4e27-833f-04a521e24487)
	- [x] Graph valid
	- [x] Exporting
	- [x] Exported
        - [x] Import Form Sent

Wei
- [CovidImmuneAtlas](https://contribute.data.humancellatlas.org/submissions/detail?uuid=639d3383-47a6-4436-985e-4eedd8ee46bb)
	- [x] Graph valid
	- [x] Exporting
	- [x] Exported
        - [x] Import Form Sent
- [humanBloodCiteSeq2](https://contribute.data.humancellatlas.org/submissions/detail?uuid=5f7fa8b1-f35b-4a2d-b385-c2a686acbc9c)
	- [x] Graph valid
	- [x] Exporting
	- [x] Exported
        - [x] Import Form Sent
- [covid19PBMCsTCRandCITEseq](https://contribute.data.humancellatlas.org/submissions/detail?uuid=5fd102f6-8368-40c3-92f6-f0fc3a557aac)
	- [x] Graph valid
	- [x] Exporting
	- [x] Exported
        - [x] Import Form Sent
- [BenchmarkingSingleCellProtocols](https://contribute.data.humancellatlas.org/submissions/detail?uuid=9321f2f2-a2de-4a2f-b113-70c42836907e)
	- [x] Graph valid
	- [x] Exporting
	- [x] Exported
        - [x] Import Form Sent

Arsenios
- [normMyometriumAtlasAndLeiomyoma](https://contribute.data.humancellatlas.org/submissions/detail?uuid=4310b292-921c-4e87-a74b-5b8e3ce48c3d)
	- [x] Graph valid
	- [x] Exporting
	- [x] Exported
        - [x] Import Form Sent
- [CD4TCellsInCrohnsDisease](https://contribute.data.humancellatlas.org/submissions/detail?uuid=e8693d0f-0d51-45e8-98bc-c9acbc0613c3)
	- [x] Graph valid
	- [x] Exporting
	- [x] Exported
        - [x] Import Form Sent
- [humanIelAndLplTlymphocytes](https://contribute.data.humancellatlas.org/submissions/detail?uuid=db5d0717-432a-4f6d-8860-623ddcf83b3b)
	- [x] Graph valid
	- [x] Exporting
	- [x] Exported
        - [x] Import Form Sent
- [RenalTumorMicroenvironment](https://contribute.data.humancellatlas.org/submissions/detail?uuid=102b38b3-789d-41d3-9a50-d804b0cb54d2)
	- [x] Graph valid
	- [x] Exporting
	- [x] Exported
        - [x] Import Form Sent

- [Landscape-ileum-colon](https://contribute.data.humancellatlas.org/submissions/detail?uuid=27302955-dd62-445c-8ba8-ad6346f8998b&project=cae461de-ecbd-482f-a5d4-11d607fc12ba)
	- [x] Graph valid
	- [x] Exporting
	- [x] Exported
        - [x] Import form filled

Ida
- [TubularCellLupusNephritis](https://contribute.data.humancellatlas.org/projects/detail?uuid=97fca723-d9e9-4263-9f67-335416086f47&tab=project)
	- [x] Graph valid --> yes, but it's currenty stuck in Submitted
	- [ ] Exporting
	- [ ] Exported
        - [ ] Import form filled  

- [HumanMelanocyteDevelopment](https://contribute.data.humancellatlas.org/projects/detail?uuid=a4f154f8-5cc9-40b5-b8d7-af90afce8a8f&tab=project)
	- [x] Graph valid --> yes, but it's currenty stuck in Submitted
	- [x] Exporting
	- [x] Exported
        - [x] Import form filled  

**Tasks**
- [x] Move all datasets to Graph Valid status
- [x] Re-deploy state tracker
- [x] Export those datasets
- [ ] Monitor exporting
- [ ] Once exported, main wrangler will be contacted to fill out import form

**Acceptance criteria for the task:**
- [ ] All datasets have been exported successfully
- [ ] All import forms have been filled

**Comment by ESapenaVentura** [comment]
## Snippets for each part

** Detect all exporting datasets** 
```python
all_submissions = api.get_all("https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes", 'submissionEnvelopes')
all_submissions = list(all_submission)
all_submissions = list(all_submissions)
exporting_submissions = [sub for sub in all_submissions if sub['submissionState'] in ['Exporting', 'Submitted']]
map_with_project_uuid = {}
for sub in exporting_submissions:
    proj = api.get(sub['_links']['projects']['href']).json()['_embedded']['projects'][0]
    map_with_project_uuid[proj['content']['project_core']['project_short_name']] = f"https://contribute.data.humancellatlas.org/submissions/detail?uuid={sub['uuid']['uuid']}"
for key, value in map_with_project_uuid.items():
    print(f'- [{key}]({value})\n\t- [ ] Graph valid\n\t- [ ] Exporting\n\t- [ ] Exported')
```

**Comment by ESapenaVentura** [comment]
**Put all datasets to submitted**
```python
responses = []
for submission in exporting_submissions:
    responses.append(api.put(submission['_links']['commitSubmit']['href']))
assert all([r.ok for r in responses])
```

**Comment by gabsie** [comment]
Action: reexport the datasets one by one, and change their status in the list above. @ESapenaVentura, yours is the first one :)

**Comment by ESapenaVentura** [comment]
I will take care of the 4 datasets. I have started re-export right now for the first of them

**Comment by ESapenaVentura** [comment]
Tried today,

- Discarded Singlecellsequencingoflungcarcinoma as it needs discussion
- The other 3 crash ingest due to memory issues. @ESapenaVentura to chat with @amnonkhen when back

**Comment by ESapenaVentura** [comment]
Tried today,

- Discarded Singlecellsequencingoflungcarcinoma as it needs discussion
- The other 3 crash ingest due to memory issues. @ESapenaVentura to chat with @amnonkhen when back

**Comment by idazucchi** [comment]
**possible explanation**
ingest checks an endpoint to check the health of the system:
if the endpoint says no/ doesn't reply --> the pod running core or the ui is killed --> this stops the export

the api calls slow down the system and keep the endpoint from reporting the health of the system

**Comment by amnonkhen** [comment]
Done today: CovidImmuneAtlas

**Comment by gabsie** [comment]
@ESapenaVentura - please enter the import form for the Covidimmuneatlas - in the list above

**Comment by amnonkhen** [comment]
covid19PBMCsTCRandCITEseq exported

**Comment by ofanobilbao** [comment]
@ESapenaVentura and @arschat to fill import forms for the first 3.

TubularCellLupusNephritis has an unlinked file (not a problem as it is a supplementary file). It is still crashing ingest.

**Comment by ofanobilbao** [comment]
Amnon is solving the issues with workarounds, reducing the number of active Exporter pods.

**Comment by amnonkhen** [comment]
Today's update:
- [HumanMelanocyteDevelopment](https://contribute.data.humancellatlas.org/projects/detail?uuid=a4f154f8-5cc9-40b5-b8d7-af90afce8a8f&tab=project) - exported
- [TubularCellLupusNephritis](https://contribute.data.humancellatlas.org/projects/detail?uuid=97fca723-d9e9-4263-9f67-335416086f47&tab=project) - still working on it. It keeps crashing ingest during the beginning of the spreadsheet generation phase (before starting the linking map so it is not related to ebi-ait/dcp-ingest-central#926)

**Comment by arschat** [comment]
@arschat to sent input for for humanmelanocytedevelopment

**Comment by ofanobilbao** [comment]
@amnonkhen any updates on [TubularCellLupusNephritis](https://contribute.data.humancellatlas.org/projects/detail?uuid=97fca723-d9e9-4263-9f67-335416086f47&tab=project ) ?

**Comment by ofanobilbao** [comment]
As agreed on Ops Review Meeting yesterday, the plan is for @amnonkhen to export the remaining project in his personal machine and let Ida know so she can submit the import form for it

**Comment by gabsie** [comment]
Closing this issue, leaving just a separate one for the last remaining dataset:

TubularCellLupusNephritis

 Graph valid --> yes, but it's currenty stuck in Submitted
 Exporting
 Exported
 Import form filled
