### ISSUE TITLE
Process changes for wave 2

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1175]
**Context**
With integration wave 2 on the horizon we need to evaluate what changes we want to make to our processes, in particular with the aim of making wrangling easier and faster.

**Resources**
[brainstorm miro board](https://miro.com/app/board/uXjVMwU1cAs=/)
[actions](https://docs.google.com/document/d/1j_eO_1BVZlft8tEPDmCg-56O4Q5djGMxMQbYW6tj3FI/edit#heading=h.byrvvji1vo9)
[Proposed wrangling changes](https://docs.google.com/document/d/1SnFGYzcsfYUZZkYU3M_Knt7yFQUsH5wk6I72WjJ-m8E/edit)

**Tasks**:
- [x] get approval for proposed wrangling changes
- [x] get scientists' opinion on need for well label in plate based techniques
~~- [ ] prepare test data~~
~~- [ ] get test data reviewed~~
- [ ] open documentation ticket --> waiting for Tier 1 metadata to be confirmed

**Comment by idazucchi** [comment]
preparing the test data
I need to email Peng and at least another lab

**Comment by idazucchi** [comment]
[Peng's reply](https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/6aC1O_DyShQ) - it sounds like the well label is valuable information for quality control, so the change in wrangling for plate based technique won't go ahead

**Comment by idazucchi** [comment]
waiting for confirmation of tier 1 metadata to discuss wrangling changes

**Comment by idazucchi** [comment]
closing this because the work for wave 2 went in a different direction and this is no longer relevant
