### ISSUE TITLE
Update hca_bionetworks for Retina v1 projects

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1228]
**Description**
Dave and the HCA exec office are working to get the Retina page up and running on the HCA Data portal

Estimated deadline: mid February

**Tasks**
- [ ] compare [2023 list](https://docs.google.com/spreadsheets/d/129T_QsKKCqJmPiwuK9qLl7uxASUplI84At6ewu2vwLA/edit#gid=1461665337) with [finalised retina list](https://docs.google.com/spreadsheets/d/1DQn5Ae9_4nrek_tj6dreSPvf8BjY1cbP/edit#gid=1657680599)
- [ ] re-export published datasets to add the hca_bionetworks field ?
- [ ] wrangle new project - [10.1016/j.devcel.2022.02.018](https://doi.org/10.1016/j.devcel.2022.02.018)

**Comment by idazucchi** [comment]
##### Comparing lists
all projects are published except for one --> [10.1016/j.celrep.2021.109994](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8642835/)
The relevant accession for this project is [GSE183684](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE183684), and after some digging I confirmed that the original publication is  [10.1016/j.devcel.2022.02.018](https://doi.org/10.1016/j.devcel.2022.02.018).
I checked with the bionetwork and they are ok with [10.1016/j.devcel.2022.02.018](https://doi.org/10.1016/j.devcel.2022.02.018) as reference publication

I will wrangle this publication for R35 so that it can be live for February

##### Backfilling
I need to confirm with Dave whether he needs us to update already published projects, it seems like the pages are still quite manual and independent from the hca_bionetworks field

**Comment by idazucchi** [comment]
| uuid                                 | status                                                        |
|--------------------------------------|---------------------------------------------------------------|
|` 1dddae6e-3753-48af-b20e-fa22abad125d` | filled in import form                                         |
| `8185730f-4113-40d3-9cc3-929271784c2b` | file invalid - dcp1 ?                                         |
| `4bec484d-ca7a-47b4-8d48-8830e06ad6db` | graph error - 16 fastq files per process, could fix manually  |
| `30dc3964-1135-4b56-b393-ce2dcbc6e379`| export failed                                                 |
| `4f4f0193-ede8-4a82-8cb0-7a0a22f06e63`| filled in import form                                         |
| `07d5987e-7f9e-4f34-b0fb-a185a35504f5`| submission complete                                           |
| `e090445c-6971-4212-bc5f-ae4ec3914102` | submission complete                                           |
| `c3354786-c17c-4e53-b4d7-c7afbed5b208` | removed atals info, no longer part of the atlas               |
| `aebc99a3-3151-482a-9709-da6802617763` | added info                                                    |

**Comment by idazucchi** [comment]
only 4 projects remaining to re-export - will be linked manaually for now

**Comment by idazucchi** [comment]
only 2 projects missing, deprioritiesd due to more urgent work on managed access
