### ISSUE TITLE
Ingestion guide for wave 2

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1231]
**Description of the task:**
Wave 2 will require some wrangling effort directly from the authors of each paper on the bionetwork list
To make the process easier the executive office is compling a submission guideline and we need to curate our section.
[Submission guidelines](https://docs.google.com/document/d/1WdsMr-qv5FE6vPcRshthXc1CXozZNNhk_VTA2QJ1jHs/edit#heading=h.qa2rzelq7xbb)

To write our submission instructions we need to first establish what we are responsible for wrangling and what will be handed off to the authors - the result of the discussion are in [this miro board](https://miro.com/app/board/uXjVN1H4u5A=/?share_link_id=810946880088)

**Tasks**
- [ ] make copy of questionnaire & edit (cxg link?)
- [ ] edit ingestion instructions
- [ ] clarify deadlin
- [ ] update quick guide for contributors --> see [here](url)

**Acceptance criteria for the task:**
- [ ] the instructions for contributors are up to date
- [ ] the submission guideline is finalised

**Comment by idazucchi** [comment]
priority --> tailor questionaire
branch questionaire - if doi no experimental info needed
else - tailor spreadsheet
