### ISSUE TITLE
Run all DCP1 datasets through the graph validator

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-wrangler-central#14]
**Description of the task:**

As a data wrangler I need to ensure the existing datasets are valid with the ingest graph validator to ensure correct data is available in the DCP2 MVP.

This task will involve running the graph validator over DCP1 spreadsheets that have been updated and validated in the UI. Any issues discovered by the validator will need to be corrected.

**Acceptance criteria for the task:**

- [ ] all DCP 1 dataset spreadsheets (latest version) ran through graph validator
- [ ] any identified mistakes fixed
- [ ] all DCP1 spreadsheets are valid according to the graph validator

**Comment by mshadbolt** [comment]
This task depends on having up to date spreadsheets to run the validator on.

**Comment by ESapenaVentura** [comment]
After some discussion we determined that this task is not blocked by having the latest up-to-date spreadsheets, as we will add the test errors to the AUDR tickets or whatever channel we'll be using to record the metadata changes.

**Comment by ESapenaVentura** [comment]
For the first part of the iteration, I will be crossing out the datasets as I run the validator on them and (if errors) write in the AUDR ticket:

- [ ] Ischaemic sensitivity of human tissue by single cell RNA seq
- [ ] Spatio-temporal immune zonation of the human kidney
- [ ] The emergent landscape of the mouse gut endoderm at single-cell resolution
- [ ] Systematic comparative analysis of single cell RNA-sequencing methods
- [ ] Structural Remodeling of the Human Colonic Mesenchyme in Inflammatory Bowel Disease
- [ ] Single cell profiling of human induced dendritic cells generated by direct reprogramming of embryonic fibroblasts
- [ ] A single-cell molecular map of mouse gastrulation and early organogenesis
- [ ] Transcriptomic classification of human retinal cell types with single-nuclei RNA-seq.
- [ ] Dissecting the human liver cellular landscape by single cell RNA-seq reveals novel intrahepatic monocyte/ macrophage populations
- [ ] A single-cell transcriptome atlas of the adult human retina
- [ ] A single-cell reference map of transcriptional states for human blood and tissue T cell activation
- [ ] The Single Cell Transcriptomic Landscape of Early Human Diabetic Nephropathy
- [ ] Profiling of CD34+ cells from human bone marrow to understand hematopoiesis
- [ ] Tabula Muris: Transcriptomic characterization of 20 organs and tissues from Mus musculus at single cell resolution
- [ ] A Single-Cell Transcriptomic Map of the Human and Mouse Pancreas Reveals Inter- and Intra-cell Population Structure
- [ ] Census of Immune Cells
- [ ] Cell hashing with barcoded antibodies enables multiplexing and doublet detection for single cell genomics
- [ ] Single Cell Transcriptomics of a Human Kidney Allograft Biopsy Defines a Diverse Inflammatory Response
- [ ] Bone marrow plasma cells from hip replacement surgeries
- [ ] 1.3 Million Brain Cells from E18 Mice
- [ ] Precursors of human CD4+ cytotoxic T lymphocytes identified by single-cell transcriptome analysis
- [ ] Assessing the relevance of organoids to model inter-individual variation
- [ ] Comparison, calibration, and benchmarking of high-throughput single cell RNA-Seq techniques for unbiased cell-type classification
- [ ] Reconstructing the human first trimester fetal-maternal interface using single cell transcriptomics
- [ ] Melanoma infiltration of stromal and immune cells
- [ ] Single-cell RNA-seq analysis of human pancreas from healthy individuals and type 2 diabetes patients
- [ ] Single-cell RNA-seq analysis throughout a 125-day differentiation protocol that converted H1 human embryonic stem cells to a variety of ventrally-derived cell types.
- [ ] Single cell transcriptome analysis of human pancreas reveals transcriptional signatures of aging and somatic mutation patterns.

**Comment by ESapenaVentura** [comment]
Apparently there are issues with the xls hydrator (Some spreadsheets won't work, others will load without all nodes and no edges),so I will be running the tool with the ingest UUIDs.

This will require a re-run once we begin updating the metadata

**Comment by rays22** [comment]
### DCP1 datasets
- These submissions have past validation by <https://github.com/ebi-ait/ingest-graph-validator/tree/master/graph_test_set>. They have a note about the validation results in the relevant AUDR tickets:

```
Project short name	Ingest submission UUID	Project name
Multiplexed scRNA-seq with barcoded antibodies	6931d821-9cd2-4ae1-acf7-62cd3b90082e	Cell hashing with barcoded antibodies enables multiplexing and doublet detection for single cell genomics
HPSI human cerebral organoids	fce97270-fce0-4744-8a4e-a93d95521852	Assessing the relevance of organoids to model inter-individual variation
Single cell RNAseq characterization of cell types produced over time in an in vitro model of human inhibitory interneuron differentiation	0948a727-228f-4cfc-857e-6243c6aed08d	Single-cell RNA-seq analysis throughout a 125-day differentiation protocol that converted H1 human embryonic stem cells to a variety of ventrally-derived cell types.
WongAdultRetina	668791ed-deec-4470-b23a-9b80fd133e1c	A single-cell transcriptome atlas of the adult human retina
Human Hematopoietic Profiling	7dbcf5ae-f8d7-487c-a3d4-794d8639a1e2	Profiling of CD34+ cells from human bone marrow to understand hematopoiesis
```

- These submissions have failed at least one validation test by <https://github.com/ebi-ait/ingest-graph-validator/tree/master/graph_test_set> or failed to load into a proper graph. I have not added any notes about the validation results in the relevant AUDR tickets:
```
Project short name	Ingest submission UUID	Project name	Failed test
TissueSensitivity   fd52efcc-6924-4c8a-b68c-a299aea1d80f	Ischaemic sensitivity of human tissue by single cell RNA seq	sequence_file_linkto_cell_suspesion.adoc; min_experimental_design_length_5.adoc; contains_cell_barcode_info.adoc; contains_umi_barcode_info.adoc; protocol_document_has_supplementary_file.adoc
KidneySingleCellAtlas   702313be-fdde-42ea-89a5-bd1b01531736	Spatio-temporal immune zonation of the human kidney imported 0 nodes; 0 edges
KidneySingleCellAtlas   9cfca427-6e22-447a-867e-4d81fdb7391c	Spatio-temporal immune zonation of the human kidney imported 0 edges
KidneySingleCellAtlas   d5410c6e-612d-421a-a66f-2de5e04dd050	Spatio-temporal immune zonation of the human kidney protocol_document_has_supplementary_file.adoc
KidneySingleCellAtlas   2afc1a93-f35d-4dec-95b7-7bd54b6da834	Spatio-temporal immune zonation of the human kidney imported 0 nodes; 0 edges
KidneySingleCellAtlas   9e1d7bdc-e4a8-4dac-a131-6434aeb15bd0	Spatio-temporal immune zonation of the human kidney imported 0 nodes; 0 edges
Mouse Endoderm Project  0fb44736-c50f-49ab-bcdc-0985e596b955	The emergent landscape of the mouse gut endoderm at single-cell resolution  10x_has_more_than_2_files.adoc
HumanColonicMesenchymeIBD HumanColonicMesenchymeIBD c51efa69-a348-46d4-9997-c7a11915d53b	Structural Remodeling of the Human Colonic Mesenchyme in Inflammatory Bowel Disease no_orphans.adoc
HumanColonicMesenchymeIBD HumanColonicMesenchymeIBD 8d2aace1-34d6-4c6c-bc4a-3af461dd7559	Structural Remodeling of the Human Colonic Mesenchyme in Inflammatory Bowel Disease contains_cell_barcode_info.adoc; contains_umi_barcode_info.adoc; 10x_has_more_than_2_files.adoc
Reprogrammed_Dendritic_Cells	4f590376-7a5e-4bdc-9ae0-a0eb16602513	Single cell profiling of human induced dendritic cells generated by direct reprogramming of embryonic fibroblasts   imported 0 edges
Reprogrammed_Dendritic_Cells	5c438071-abc3-4b34-8f55-d90bfe29c404	Single cell profiling of human induced dendritic cells generated by direct reprogramming of embryonic fibroblasts   no_orphans.adoc; 10x_has_more_than_2_files.adoc
Reprogrammed_Dendritic_Cells	8c45a848-ab32-4928-8dd6-567b75eaf7e1	Single cell profiling of human induced dendritic cells generated by direct reprogramming of embryonic fibroblasts   imported 0 edges
snRNA-seq_for_human_retina  7d515499-b5b6-4083-95cd-6a393344865e	Transcriptomic classification of human retinal cell types with single-nuclei RNA-seq.   10x_has_more_than_2_files.adoc; ensure_lane_index.adoc
SingleCellLiverLandscape	1e2601a5-8938-446c-bbb3-1f37a84b11da	Dissecting the human liver cellular landscape by single cell RNA-seq reveals novel intrahepatic monocyte/ macrophage populations	10x_has_more_than_2_files.adoc
HumanTissueTcellActivation  8b5feb5e-9039-4c54-9e79-053e490c141a	A single-cell reference map of transcriptional states for human blood and tissue T cell activation  imported 0 edges
HumanTissueTcellActivation  cad1dcdd-f49a-4f9c-9417-359b0e5bdd12	A single-cell reference map of transcriptional states for human blood and tissue T cell activation  ensure_seq_libr_prep_protocols.adoc
Diabetic Nephropathy snRNA-seq  a69c731b-9db7-45e3-938f-daf2e4636a6e	The Single Cell Transcriptomic Landscape of Early Human Diabetic Nephropathy	10x_has_more_than_2_files.adoc
1M Immune Cells 85e72912-9f91-4489-8169-3b43cc65a16a	Census of Immune Cells  10x_has_more_than_2_files.adoc
Kidney biopsy scRNA-seq 588281cb-93e2-4888-b75e-5cee5e39fc7f	Single Cell Transcriptomics of a Human Kidney Allograft Biopsy Defines a Diverse Inflammatory Response  protocol_document_has_supplementary_file.adoc
Drop-seq, DroNc-seq, Fluidigm C1 Comparison bf3116e5-1af1-46c2-8bbd-44dac49d1e7f	Comparison, calibration, and benchmarking of high-throughput single cell RNA-Seq techniques for unbiased cell-type classification contains_umi_barcode_info.adoc
scFetalPaedIBDGut   dca729d5-e66c-476b-a646-632c4499820b	Single-cell sequencing of developing human gut reveals transcriptional links to childhood Crohn’s disease   imported 0 nodes; 0 edges 
AdultHemOrgans  7a24654c-1b54-497e-82b7-c793ede4a02f	Transcriptomic characterisation of haematopoietic stem and progenitor cells from human adult bone marrow, spleen and peripheral blood  imported 0 nodes; 0 edges 
AdultHemOrgans  e470b46e-2160-4f69-a1e3-524a09951e90	Transcriptomic characterisation of haematopoietic stem and progenitor cells from human adult bone marrow, spleen and peripheral blood  imported 0 nodes; 0 edges 
```


- I have not yet validated these datasets:
```
Project short name	Ingest submission UUID	Project name
CD4+ cytotoxic T lymphocytes	3bb965cb-2a6f-4802-a4f2-52d0423e6ecc	Precursors of human CD4+ cytotoxic T lymphocytes identified by single-cell transcriptome analysis
Healthy and type 2 diabetes pancreas	c81f7d54-a27f-4212-a6df-88dde947f7cc	Single-cell RNA-seq analysis of human pancreas from healthy individuals and type 2 diabetes patients
scRNAseqSystemicComparison	d1610c4a-76c6-4b69-af63-c74af869fa75	Systematic comparative analysis of single cell RNA-sequencing methods
MouseGastrulationAtlas	19c5c89a-7bfb-4b4d-9ff5-3ef009304ba5	A single-cell molecular map of mouse gastrulation and early organogenesis
Tabula Muris	14df1f92-155c-4da2-97fc-85601dee64da	Tabula Muris: Transcriptomic characterization of 20 organs and tissues from Mus musculus at single cell resolution
BM_PC	67abd7a1-644b-48d0-b8b8-251d8195a742	Bone marrow plasma cells from hip replacement surgeries
1M Neurons	064d36ca-ea4d-428f-b30f-0cf5e5350a9d	1.3 Million Brain Cells from E18 Mice
Single cell transcriptome analysis of human pancreas	5cd8b827-e4fa-4ffa-86f5-f0f8302baee9	Single cell transcriptome analysis of human pancreas reveals transcriptional signatures of aging and somatic mutation patterns.
HumanMousePancreas	7b4cd093-bfa5-477e-9c95-69bafc1cb6bf	A Single-Cell Transcriptomic Map of the Human and Mouse Pancreas Reveals Inter- and Intra-cell Population Structure
Fetal/Maternal Interface	46fe8bd7-329b-4f09-b227-5ee48c109c16	Reconstructing the human first trimester fetal-maternal interface using single cell transcriptomics
Mouse Melanoma	4756b97c-3666-4ff0-9c48-611dc06b7740	Melanoma infiltration of stromal and immune cells
``` 

### New datasets for DCP2
- These non-DCP1 submissions failed to load into the ingest-graph-validator:
```
Project short name	Ingest submission UUID	Project name
scFetalPaedIBDGut	dca729d5-e66c-476b-a646-632c4499820b	Single-cell sequencing of developing human gut reveals transcriptional links to childhood Crohn’s disease
AdultHemOrgans	7a24654c-1b54-497e-82b7-c793ede4a02f	Transcriptomic characterisation of haematopoietic stem and progenitor cells from human adult bone marrow, spleen and peripheral blood
AdultHemOrgans	e470b46e-2160-4f69-a1e3-524a09951e90	Transcriptomic characterisation of haematopoietic stem and progenitor cells from human adult bone marrow, spleen and peripheral blood
```

- The spreadsheet `s-subs4-validatedFASTQ.xlsx` has failed validation of tests [10x_has_more_than_2_files.adoc](https://github.com/ebi-ait/ingest-graph-validator/blob/master/graph_test_set/10x_has_more_than_2_files.adoc) and [ensure_seq_libr_prep_protocols.adoc](https://github.com/ebi-ait/ingest-graph-validator/blob/master/graph_test_set/ensure_seq_libr_prep_protocols.adoc)
It belongs to non-DCP1 dataset:

```
Project short name	Project name
AdultHemOrgans	Transcriptomic characterisation of haematopoietic stem and progenitor cells from human adult bone marrow, spleen and peripheral blood
```

**Comment by rays22** [comment]
I have not been able to load into the `ingest-graph-validator` the metadata of the following non-DCP1 datasets:
* Single-cell sequencing of developing human gut reveals transcriptional links to childhood Crohn’s disease (submission `dca729d5-e66c-476b-a646-632c4499820b`)
* Single-cell transcriptional landscape of human embryonic limb development
* Transcriptomic characterisation of haematopoietic stem and progenitor cells from human adult bone marrow, spleen and peripheral blood (submissions `7a24654c-1b54-497e-82b7-c793ede4a02f` or `e470b46e-2160-4f69-a1e3-524a09951e90`)

**Comment by ESapenaVentura** [comment]
Are you loading them with the ingest hydrator?

If so, can you try changing the environmental variable with `export INGEST_GRAPH_VALIDATOR_INGEST_API_URL="https://api.ingest.archive.data.humancellatlas.org"` and try to load them again? I think the old ingest API is set by default, and that one doesn't have those datasets

**Comment by rays22** [comment]
> Are you loading them with the ingest hydrator?
> 
> If so, can you try changing the environmental variable with `export INGEST_GRAPH_VALIDATOR_INGEST_API_URL="https://api.ingest.archive.data.humancellatlas.org"` and try to load them again? I think the old ingest API is set by default, and that one doesn't have those datasets

OK, I'll try that.

**Comment by justincc** [comment]
In 2020-06-15 Mon standup @rays22 discussed that the remaining datasets are too large to validate on his desktop. This means we'll need to execute them on an AWS instance, which requires developer operational support. So now waiting on this. @ESapenaVentura may have further comments.

**Comment by rays22** [comment]
> In 2020-06-15 Mon standup @rays22 discussed that the remaining datasets are too large to validate on his desktop. This means we'll need to execute them on an AWS instance, which requires developer operational support. So now waiting on this. @ESapenaVentura may have further comments.

The ingest-graph-validator running on my laptop never finishes validation of datasets with a large number of nodes (entities).
For example, dataset
`Tabula Muris	14df1f92-155c-4da2-97fc-85601dee64da`
has 407556 nodes and the validation process appears to hang after about 20 hours with errors like

>[connectionpool.py:662 -              urlopen() ] 2020-06-12 06:10:35,544 - urllib3.connectionpool - WARNING - Retrying (Retry(total=49, connect=None, read=9, redirect=None, status=10)) after connection broken by 'ProtocolError('Connection aborted.', OSError("(101, 'ENETUNREACH')",))': /biomaterials/5d24ef4e88fa640008b069cc/derivedByProcesses

**Comment by rays22** [comment]
1. The following non-DCP1 dataset has passed cross-entity validation:

>scFetalPaedIBDGut | dca729d5-e66c-476b-a646-632c4499820b | Single-cell sequencing of developing human gut reveals transcriptional links to childhood Crohn’s disease

2. The following non-DCP1 dataset has failed cross-entity validation, because of missing lane indices:

>AdultHemOrgans | 7a24654c-1b54-497e-82b7-c793ede4a02f | Transcriptomic characterisation of haematopoietic stem and progenitor cells from human adult bone marrow, spleen and peripheral blood | densure_lane_index.adoc

**Comment by rays22** [comment]
Hi @justincc ,
Could you or another dev kindly install the
<https://github.com/ebi-ait/ingest-graph-validator>
on EC2 tool.archive.data.humancellatlas.org
or on a similar server so that the cross-entity validation tests can be run on large datasets?
It would be great if the ingest-graph-validator could be run as a non-admin user.
I would like to note that the pypi package is not up-to-date compared with the github repo version at <https://github.com/ebi-ait/ingest-graph-validator> (so we need the github version).

I can only run a single validation sessions with my setup on my laptop. It appears to me that the ingest-graph-validator can create ('hydrate') only a single graph database instance. If you start another ingest-graph-validator process, it just overwrites the same single database. Because of that, I can not run parallel validation sessions.
Would it be possible to set up parallel instances of the ingest-graph-validator to process more than one dataset at once?
Thanks!

**Comment by rays22** [comment]
The following DCP1 datasets do not have any cross-entity errors:

* AUDR | Project short name | Ingest submission UUID | Project name
* <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/177> | Fetal/Maternal Interface | 46fe8bd7-329b-4f09-b227-5ee48c109c16 | Reconstructing the human first trimester fetal-maternal interface using single cell transcriptomics
* <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/349> | Single cell RNAseq characterization of cell types produced over time in an in vitro model of human inhibitory interneuron differentiation | 0948a727-228f-4cfc-857e-6243c6aed08d | Single-cell RNA-seq analysis throughout a 125-day differentiation protocol that converted H1 human embryonic stem cells to a variety of ventrally-derived cell types.
* <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/350> | Single cell transcriptome analysis of human pancreas | 5cd8b827-e4fa-4ffa-86f5-f0f8302baee9 | Single cell transcriptome analysis of human pancreas reveals transcriptional signatures of aging and somatic mutation patterns.
* <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/354> | Human Hematopoietic Profiling | 7dbcf5ae-f8d7-487c-a3d4-794d8639a1e2 | Profiling of CD34+ cells from human bone marrow to understand hematopoiesis
* <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/357> | HPSI human cerebral organoids | fce97270-fce0-4744-8a4e-a93d95521852 | Assessing the relevance of organoids to model inter-individual variation
* <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/362> | Multiplexed scRNA-seq with barcoded antibodies | 6931d821-9cd2-4ae1-acf7-62cd3b90082e | Cell hashing with barcoded antibodies enables multiplexing and doublet detection for single cell genomics
* <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/368> | WongAdultRetina | 668791ed-deec-4470-b23a-9b80fd133e1c | A single-cell transcriptome atlas of the adult human retina
* This dataset is not in DCP1: | scFetalPaedIBDGut | dca729d5-e66c-476b-a646-632c4499820b | Single-cell sequencing of developing human gut reveals transcriptional links to childhood Crohn’s disease
