### ISSUE TITLE
Create a new SOP to update the Dataset Tracking Sheet

### ISSUE THREAD

**Issue by rays22** [ebi-ait/hca-ebi-wrangler-central#140]
**Description of the task:**

Create a new SOP on who, when and how should update the [Dataset Tracking Sheet](https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/).

* How often the [Dataset Tracking Sheet](https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/) should be updated?
* Who are responsible updating the [Dataset Tracking Sheet](https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/)?
* What is the minimum information to include when adding a new record?
* What tools can facilitate the updates?

**Acceptance criteria for the task:**
The SOP should provide answers to the following questions as a minimum:
* [x] How often the [Dataset Tracking Sheet](https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/) should be updated?
* [x] Who are responsible updating the [Dataset Tracking Sheet](https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/)?
* [x] What is the minimum information to include when adding a new record?
* [x] What tools can facilitate the updates?

**Comment by lauraclarke** [comment]
@mshadbolt do you think the meeting tomorrow will get answers to these questions?

**Comment by mshadbolt** [comment]
I am hoping so, thanks for pointing our the ticket.

**Comment by lauraclarke** [comment]
I am reviewing what is in operations to close stuff that isn't useful

**Comment by lauraclarke** [comment]
@mshadbolt @rays22 @ami-day I have shifted this to the sprint backlog, for now, I am hoping this can be completed so the first iteration of this can be run during this sprint

**Comment by ESapenaVentura** [comment]
I have written a proposal about this [here](https://docs.google.com/document/d/10yjBLGpxBoyjZORWXnBaGeq1yf17klWcNtbCt8eU9b0/edit#) 

I have not had time to work on that proposal for some time but I think it answers most of the questions posed here

**Comment by ESapenaVentura** [comment]
With the SOP created https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/dataset_acknowledgement_SOP.html I believe we are done with this.

Moving it to Done!
