### ISSUE TITLE
Onboarding tasks for Wei

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-wrangler-central#200]
# Tasks

Welcome to the HCA DCP! We are pleased to introduce you to the data wrangling team. Before beginning to work by yourself, you'll be asked to complete a set of tasks and meetings. These will guide you through both the general and specifics of your role, and it will help us make sure you understand how we work in the team. Your introductory tasks are:

- [x] Read the Onboarding doc. https://ebi-ait.github.io/hca-ebi-wrangler-central/ebi-wrangler-onboarding.html
- [x] Clone all the following repos to your computer: 
  - [x] [hca-ebi-wrangler-central](https://github.com/ebi-ait/hca-ebi-wrangler-central)
  - [x] [metadata-schema](https://github.com/HumanCellAtlas/metadata-schema)
  - [x] [Spreadsheet generator](https://github.com/HumanCellAtlas/schema-template-generator)
  - [x] [ingest-graph-validator](https://github.com/ebi-ait/ingest-graph-validator)
  - [x] [geo-to-hca](https://github.com/ebi-ait/geo_to_hca)

- [x] Locate all the metadata schemas and documents regarding SOPs. 

## General tasks

These are more wrangling-specific tasks. They will provide you with the basic knowledge necessary to perform your future tasks in the team. These include:
1. Watch HCA Metadata Standard 101 [video](https://drive.google.com/open?id=12hGA3_ARTKl-W0JxMKm8fHqvx31L3Ohf) ([slides](https://drive.google.com/open?id=1CJZfFpVFPolYPf30NSNn3A4CPVHmbfbaHUKlzCqBz_c)).
1. Familiarise yourself with the projects and Standard Operating Procedures (SOPs) inside the [hca-wrangling documentation website](https://ebi-ait.github.io/hca-ebi-wrangler-central/).
1. Familiarise yourself with the graph structure and the model that is being used.
1. Get familiarised with the [spreadsheet generator](https://github.com/HumanCellAtlas/schema-template-generator).
1. Read up on FAIR Data Principles
    - [The FAIR Guiding Principles for scientific data management and stewardship (Wilkinson 2016)](https://www.nature.com/articles/sdata201618)
    - [A design framework and exemplar metrics for FAIRness (Wilkinson 2018)](https://www.nature.com/articles/sdata2018118)
    - [Quick summary](https://www.force11.org/group/fairgroup/fairprinciples) of FAIR Data Principles
    - Also related: [Uniform resolution of compact identifiers for biomedical data (Wimalaratne 2018)](https://www.nature.com/articles/sdata201829)

# Onboard Meetings

These meetings will help you understand some aspects of the work here, as well as our work policy and important details about what technologies we use. They will be short (around 30 minutes) and you should try to get at least one per day. You will be expected to book the meeting with the person that is supposed to give it.

1. Introduction to agile: The manifesto and basic concepts. Project Manager (PM), Product Owner (PO), sprint, standup, tickets and story points. @clairerye will do this
1. Computational environments: AIT - Wrangler/dev Github workflow, recommended software (PyCharm, sublime, google sync, notes, postman). @mshadbolt 
1. Wrangling repository: Tools, vignettes, tickets, and processes. @mshadbolt 
1. Spreadsheet generator: The spreadsheets and the contributor form. General tour and how to generate one. @mshadbolt 
1. Metadata repository 1: Entities structure: core, type and module. Graphs as a tool to represent a project. @ESapenaVentura 
1. Metadata repository 2: Introduction to JSON, schema evolution and versioning.@ESapenaVentura 
1. Technologies: 10x, SMART-Seq2, Imaging transcriptomics, CITE-Seq, ATAC-Seq @ami
1. [x] Linked knowledge: Quick introduction to ontologies. @rays22 
1. HCA background: DCP organisation, stakeholders and consortia. @lauraclarke 
1. Ingest: Overview of ingest infrastructure. @jacobwindsor @aaclan-ebi 

# Acceptance criteria

- [ ] Finish all the tasks outlined.
- [ ] Close this issue.

**Comment by mshadbolt** [comment]
@ami-day @ESapenaVentura @clairerye @lauraclarke @jacobwindsor @aaclan-ebi @rays22 

I have assigned you some onboarding meetings with Wei, if you are happy to take on these can you please schedule in meetings with him this week? If you have any questions or concerns let me know. Thanks!

**Comment by ami-day** [comment]
> @ami-day @ESapenaVentura @clairerye @lauraclarke @jacobwindsor @aaclan-ebi @rays22
> 
> I have assigned you some onboarding meetings with Wei, if you are happy to take on these can you please schedule in meetings with him this week? If you have any questions or concerns let me know. Thanks!

Yea, will schedule a meeting with him for this week.

**Comment by rays22** [comment]
We had the onboarding meeting [Linked knowledge: Quick introduction to ontologies](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/200) on Dec. 17, 2020.
