### ISSUE TITLE
Write down tickets for all datasets ready for export

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#246]
**Description of the issue**

In advance for the next data release, we need to prepare a list of the datasets that are ready to export and which wranglers will be responsible to collect and upload the contributor-generated matrices as per this [SOP](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/contributor_matrix_addition_SOP.html)

**Tickets**

- [ ] [GSE119212 - Decoding the development of human hippocampus](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/193) @ESapenaVentura 
- [ ] [GSE139324 - HnsccImmuneLandscape](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/172) @ESapenaVentura 
- [x] [Stimulated peripheral blood mononuclear cells ](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/83) - Received matrices from contributor
- [x] Thymus JP #91 - @mshadbolt 
- [x] [TCellsCentralNervousSystem](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/221) received gene expression matrices from authors @ami-day 
- [x] [HealthyAndDiabeticPancreas](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/189) have obtained gene matrices and cell annotations file @ami-day 
- [x] [HumanLiverImmuneCells](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/180) matrices and annotations have been obtained @ami-day 
- [x] [TCellsNeuroinflammation](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/219) ami has emailed the authors and emailed again as a reminder on 10/02/2021 @Wkt8 
- [x]  [HumanAdiposeTissue](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/35) this author has not responded to my email and this has happened before in this past with this particular dataset. I think we can assume we cannot obtain them for this dataset @Wkt8 
- [x]  [ComprehensiveTranscriptomicsHumanKidney](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/186) - this dataset has now been removed and labelled as unsuitable in the tracker
- [x] [HumanBrainSubstantiaNigra](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/174) @Wkt8 
- [ ] [EpithelialDiversityHealthInflammation](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/220) ami has emailed. They have sent us cell annotations in an ok format but they sent us t-SNE embeddings instead of an expression matrix. I have responded to their email asking for a gene expression matrix @ESapenaVentura 
- [x] [UpdateS-SUBS-4](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/211) - received h5ad file from contributor @rays22 

**Acceptance criteria**

- [x] Each wrangler to write down all the tickets for the datasets that we will be exporting for the DCP2 Feb release by editing this ticket

- [x] Assign all datasets to wranglers to gather the CGMs

**Comment by ESapenaVentura** [comment]
@ebi-ait/hca-wranglers please tick the dataset once you've got all the matrices uploaded!

**Comment by mshadbolt** [comment]
I uploaded JPs

**Comment by ESapenaVentura** [comment]
Received matrices for citeseqpbmc dataset - Uploaded now

**Comment by ESapenaVentura** [comment]
No response for the other 2 public datasets
