### ISSUE TITLE
Fix datasets with incorrect BAM files to have FASTQ files

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#250]
**Description of the task:**

Following on from a discussion about the BAM file header issue (see [here](https://docs.google.com/document/d/132yTXvDfL9Dzwt3eUrvTmrvpDhw5PSUKmqcTScpAxvE/edit?usp=sharing) we decided to go with option 3, which is uploading the raw r1, r2 and index fastq files to the ENA, once it can accept multiple fastq files, via us specifying a fastq file identity in the xml. 

Writing a ticket so we don't forget about this, and attaching this [spreadsheet](https://drive.google.com/file/d/1jE2URktUHDBBJzFAi8IuWrk1DC0SHUeK/view?usp=sharing) which shows what we have archived, and what needs to be updated with new fastq files. Two archived submissions do not need to be updated in that they do not have mislabelled data (users can get all data from them). 

**Acceptance criteria for the task:**

- The archived submissions that need to be changed, now have all of their raw fastq files in ENA. 

Fix all the above submissions with UUIDs:
- [x] #519
- [x] #520
- [x] #521
- [x] #522
- [x] #523
- [x] #524
- [x] #525
- [x] #526
- [x] #527
- [x] #528 
- [x] fce97270-fce0-4744-8a4e-a93d95521852
- [x] #654
- [x] #681
- [x] #682

**Comment by clairerye** [comment]
The work has been done in ENA to allow for the submission of more than 2 fastq files, so this is now possible.

**Comment by Wkt8** [comment]
The archived files have BAM files. We want to append appropriate raw fastq read1, read2, and index files to these entries. 

The raw data for these projects might still be present in ingest staging areas. There may be some work for a wrangler to track them down. 

We will also want to amend the archiving SOP to include adding raw fastqs (r1, r2, index).

**Comment by Wkt8** [comment]
Speak to @ESapenaVentura when picking up this ticket!

**Comment by Wkt8** [comment]
Actions required:

- [ ] Contact ENA to figure out if we have the data access permissions to do this in the first place (contact their helpdesk?) ENA-helpdesk@ebi.ac.uk

- [ ] Figure out an SOP for doing this / create a script to do this. This requires appending lots of different files for multiple projects (see spreadsheet in initial post). They do have CLI interfaces.

**Comment by ESapenaVentura** [comment]
Jacob and I had a meeting - AI:

- [ ] @ESapenaVentura will send an email to ENA
- [ ] @ESapenaVentura Identify submissions that need to be updated (Continuation of https://drive.google.com/file/d/1jE2URktUHDBBJzFAi8IuWrk1DC0SHUeK/view)
    - [ ] Create a spreadsheet with submission UUID, run accession and CloudUrl

Optional AI (if time)
- [ ] Check if files are in cloudUrl

No immediate actions for @jacobwindsor because there is a higher priority task, but for when there is time:

- [ ] If files are not in cloudUrl, figure out where to get them (May need a wrangler)
- [ ] Once gathered, based on ENA's response, figure out how to push the new data files (Directly/through DSP, permissions needed)
- [ ] Push the data files to the proper accessions
- [ ] Check correct pairing/upload (Probably using ENA's API)

**Comment by ESapenaVentura** [comment]
About point one:
I have created a google sheet (continuation of the previous one) with the information required:
https://docs.google.com/spreadsheets/d/1PkoiGKVeQIF3FQAtwl8vhqt5CwEZfQL2zVA83bWBj6g/edit#gid=2088805478

Only 1 submission is missing the run accessions, the TissueStability dataset

**Comment by ESapenaVentura** [comment]
I sent an email to ENA

Also, I checked all files are in the respective CloudURL, and marked it in the spreadsheet

**Comment by aaclan-ebi** [comment]
This isn't a priority for this sprint. Moving this to Ops Backlog.

**Comment by ofanobilbao** [comment]
@ofanobilbao will split the ticket into one ticket per dataset, so that we can tackle 1-2 datasets per sprint fixed

**Comment by amnonkhen** [comment]
@ESapenaVentura to convert ticket to epic and attach sub tickets :)
