### ISSUE TITLE
missing cell counts from projects in the browser

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-wrangler-central#295]
There are 25 projects in https://data.humancellatlas.org/explore/projects that have unspecified cell counts (sort by the cell count in the explore table)

The total cell count is one of the primary measures of growth in the DCP
The current cell count comes from the number of cells in a cell suspension which is an optional field that is difficult to complete.

We need to identify a better way to provide an estimated cell count for every project. This does not need to be a super precise or accurate figure but a headline number like you might see in a publication abstract

https://github.com/HumanCellAtlas/metadata-schema/issues/1343 is one possible option to derive this information 

### Add cell count estimate and export
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=074a9f88-729a-455d-bca5-0ce80edf0cea
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=20f37aaf-caa1-40e6-9123-be6ce8feb2d6 
    - READY TO EXPORT BUT HAS GRAPH VALIDATOR ERRORS REGARDING ORPHANED ENTITIES @ami-day 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=403c3e76-6814-4a2d-a580-5dd5de38c7ff
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=414acced-eba0-440f-b721-befbc5642bef
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=4af795f7-3e1d-4341-b867-4ac0982b9efd
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=504e0cee-1688-40fa-b936-361c4a831f87
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=74493e98-44fc-48b0-a58f-cc7e77268b59
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=783c9952-a4ae-4106-a6ce-56f20ce27f88
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=79b13a2a-9ca1-42a4-97bd-70208a11bea6
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=8787c238-89ef-4636-a57d-3167e8b54a80
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=8d566d35-d8d3-4975-a351-be5e25e9b2ea
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=a80a63f2-e223-4890-81b0-415855b89abc
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=d012d476-8f8c-4ff3-89d6-ebbe22c1b5c1
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=dd7f2436-0c56-4709-bd17-e526bba4cc15
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=e526d91d-cf3a-44cb-80c5-fd7676b55a1d
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=ede2e0b4-6652-464f-abbc-0b2d964a25a0
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=faeedcb0-e046-4be7-b1ad-80a3eeabb066

### Export

- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=5116c081-8be7-49c5-8ce0-73b887328aa9
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=5b5f05b7-2482-468d-b76d-8f68c04a7a47
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=b4a7d12f-6c2f-40a3-9e35-9756997857e3
   - MISSING FILES @ami-day 

## Acceptance criteria

- [ ] Action on each subsection is taken for all datasets
- [ ] Import form is filled for all datasets

**Comment by ami-day** [comment]
Stalled for now - we are waiting for schema updates re: the cell count estimate.

**Comment by ofanobilbao** [comment]
The number of projects missing cell count in the browser has gone up since the ticket was created. There are currently 47 projects missing the cell count.

**Comment by ofanobilbao** [comment]
I have linked this ticket to the Migration ticket on the Dev Board. I believe once the blocking ticket is done, this will also be complete.

**Comment by ofanobilbao** [comment]
Still around 70 projects don't show a Cell Count Estimation in the Browser

**Comment by ipediez** [comment]
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=04ad400c-58cb-40a5-bc2b-2279e13a910b
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=07073c12-8006-4710-a00b-23abdb814904
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=074a9f88-729a-455d-bca5-0ce80edf0cea
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=0fd8f918-62d6-4b8b-ac35-4c53dd601f71
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=116965f3-f094-4769-9d28-ae675c1b569c
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=2043c65a-1cf8-4828-a656-9e247d4e64f1
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=2084526b-a66f-4c40-bb89-6fd162f2eb38
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=2086eb05-10b9-432b-b7f0-169ccc49d270
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=20f37aaf-caa1-40e6-9123-be6ce8feb2d6
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=348d28b0-1a70-4dc2-9cf1-fce5186131e9
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=248fcf03-16c6-4a41-b6cc-aad4d894ca42
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=24c654a5-caa5-440a-8f02-582921f2db4a
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=2ad191cd-bd7a-409b-9bd1-e72b5e4cce81
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=e4b2e4d9-2b9b-46cf-b0e0-bb23ff28030a
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=2b38025d-a5ea-4c0f-b22e-367824bcaf4c
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=2ef3655a-973d-4d69-9b41-21fa4041eed7
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=2f676143-80c2-4bc6-b7b4-2613fe0fadf0
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=31887183-a72c-4308-9eac-c6140313f39c
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=38e44dd0-c3df-418e-9256-d0824748901f
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=403c3e76-6814-4a2d-a580-5dd5de38c7ff
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=414acced-eba0-440f-b721-befbc5642bef
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=41fb1734-a121-4616-95c7-3b732c9433c7
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=42d4f8d4-5422-4b78-adae-e7c3c2ef511c
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=4a95101c-9ffc-4f30-a809-f04518a23803
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=4af795f7-3e1d-4341-b867-4ac0982b9efd
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=50151324-f3ed-4358-98af-ec352a940a61
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=504e0cee-1688-40fa-b936-361c4a831f87
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=5116c081-8be7-49c5-8ce0-73b887328aa9
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=520afa10-f9d2-4e93-ab7a-26c4c863ce18
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=54aaa409-dc28-48c5-be26-d368b4a5d5c6
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=591af954-cdcd-4839-96d3-a0d1b1e885ac
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=5b5f05b7-2482-468d-b76d-8f68c04a7a47
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=c535ac1f-1902-43bc-86a5-1e1643a5578e
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=5ee710d7-e2d5-4fe2-818d-15f5e31dae32
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=602628d7-c038-48a8-aa97-ffbb2cb44c9d
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=65858543-530d-48a6-a670-f972b34dfe10
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=67a3de09-45b9-49c3-a068-ff4665daa50e
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=68df3629-d2d2-4eed-b0ab-a10e0f019b88
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=7027adc6-c9c9-46f3-84ee-9badc3a4f53b
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=74493e98-44fc-48b0-a58f-cc7e77268b59
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=fc934a13-4a98-4901-8208-590534cd7b87
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=769a08d1-b8a4-4f1e-95f7-6071a9827555
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=783c9952-a4ae-4106-a6ce-56f20ce27f88
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=79b13a2a-9ca1-42a4-97bd-70208a11bea6
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=7ac8822c-4ef0-4194-adf0-74290611b1c6
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=7adede6a-0ab7-45e6-9b67-ffe7466bec1f
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=7b947aa2-43a7-4082-afff-222a3e3a4635
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=7c75f07c-608d-4c4a-a1b7-b13d11c0ad31
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=8787c238-89ef-4636-a57d-3167e8b54a80
- [ ] https://data.humancellatlas.org/explore/projects/87d52a86-bdc7-440c-b84d-170f7dc346d9
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=a6ac6702-1938-436f-8437-67d08161fdeb
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=8d566d35-d8d3-4975-a351-be5e25e9b2ea
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=f4019385-a929-4b82-b643-74cc728d37d1
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=955dfc2c-a8c6-4d04-aa4d-907610545d11
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=95f07e6e-6a73-4e1b-a880-c83996b3aa5c
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=962bd805-eb89-4c54-bad2-008e497d1307
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=996120f9-e84f-409f-a01e-732ab58ca8b9
- [ ] https://data.humancellatlas.org/explore/projects/a004b150-1c36-4af6-9bbd-070c06dbc17d
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=a39728aa-70a0-4201-b0a2-81b7badf3e71
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=a60803bb-f7db-45cf-b529-95436152a801
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=a80a63f2-e223-4890-81b0-415855b89abc
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=a9c022b4-c771-4468-b769-cabcf9738de3
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=abe1a013-af7a-45ed-8c26-f3793c24a1f4
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=87e600d2-57ca-4f16-addd-d357ab2f24ee
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=b4a7d12f-6c2f-40a3-9e35-9756997857e3
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=c31fa434-c9ed-4263-a9b6-d9ffb9d44005
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=c41dffbf-ad83-447c-a0e1-13e689d9b258
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=c5ca43aa-3b2b-4216-8eb3-f57adcbc99a1
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=c5f46615-68de-4cf4-bbc2-a0ae10f08243
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=c715cd2f-dc7c-44a6-9cd5-b6a6d9f075ae
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=d012d476-8f8c-4ff3-89d6-ebbe22c1b5c1
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=d3a4ceac-4d66-4984-9704-2570c0647a56
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=d7845650-f6b1-4b1c-b2fe-c0795416ba7b
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=daf9d982-7ce6-43f6-ab51-272577290606
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=dd7f2436-0c56-4709-bd17-e526bba4cc15
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=df88f39f-01a8-4b5b-92f4-3177d6c0f242
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=e526d91d-cf3a-44cb-80c5-fd7676b55a1d
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=e5d45579-1f5b-48c3-b568-320d93e7ca72
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=e8808cc8-4ca0-4096-80f2-bba73600cba6
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=ede2e0b4-6652-464f-abbc-0b2d964a25a0
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=ef1d9888-fa86-47a4-bb72-0ab0f20f7004
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=b11acd8b-25cd-453e-a654-f7af80713ce9
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=f48e7c39-cc67-4055-9d79-bc437892840c
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=f83165c5-e2ea-4d15-a5cf-33f3550bffde
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=faeedcb0-e046-4be7-b1ad-80a3eeabb066

**Comment by Wkt8** [comment]
@ESapenaVentura to post a list of all the projects which do not have a project.cell_count_estimate in INGEST. Then we can divide it up between wranglers.

**Comment by ESapenaVentura** [comment]
From the projects above:

### Lattice datasets
We can't modify these:
- e4b2e4d9-2b9b-46cf-b0e0-bb23ff28030a
- fc934a13-4a98-4901-8208-590534cd7b87
- a6ac6702-1938-436f-8437-67d08161fdeb
- 87e600d2-57ca-4f16-addd-d357ab2f24ee

(I'll update this comment as I go through)

**Comment by ESapenaVentura** [comment]
I have updated the ticekt with what all I could find

In total there. are 21 **datasets that we need to take action on**:
- 17 without cell count neither in ingest nor in the staging area
- 3 with cell count in ingest but not in the staging area
- 1 ingest dataset

**Comment by gabsie** [comment]
Action: distribute the datasets to act upon, made each dataset onto a task

**Comment by ofanobilbao** [comment]
Each dataset that needs action has an independent ticket, all linked into this ticket, which has become an epic

**Comment by ofanobilbao** [comment]
There is one ticket remaining to complete that I have removed from the epic as it is a complicated one and has been stuck forever. Closing the epic and keeping only that dataset ticket open.
