### ISSUE TITLE
Experimental Dataset tracking sheet curation

### ISSUE THREAD

**Issue by rays22** [ebi-ait/hca-ebi-wrangler-central#318]
The objective is to do a quantitative experiment to **help estimate how much time** would be needed to fill in the gaps in the [Dataset tracking sheet](https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/). By gaps I mean the gaps in the fields that are necessary to determine eligibility and priority of datasets.
This is part of the efforts to help streamline the discovery and triage stages of the data life cycle.
- [x] Circulate a list of minimum fields to fill in for triage.
- [ ] Each wrangler to curate rows in the Dataset tracking sheet for 1 hour. Report back on how many rows they managed to curate with regards to eligibility and triage information.
- [x] Collect and collate numbers.
- [x] Summarise results.

**Comment by rays22** [comment]
Experiment:
1. Set aside **1 hour** to curate dataset rows in the [Datast Tracking Sheet](https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/) with the status of none (empty cells) or `acknowledged`.
As of today, there are 43 rows with empty `hca_status`. Please, start with these.
Then move on to `acknowledged` rows with sparse content.
The current suitability and priority information is in the document [define HCA eligibility criteria “once and for all”](https://docs.google.com/document/d/1mkRIRyHe25UkJ1yKfGqSrFxXed0bqRcaJ-SMKFFEmEk/).
2. Fill in the fields necessary for eligibility and triage.
When you find a new dataset suitable for wrangling, then set its status to `uncurated`.
3. Please, record in the ticket below how many rows you managed to curate in **1 hour** and the `dcp_id` of any new datasets you found that would be suitable for wrangling.

I think these are the essential fields to fill in:

```
contributor_involved
hca_pub
hca_status
data_available
access_permission
organism
sample_type
health_status
organ
cell_count_estimate
date_added
```

**Comment by Wkt8** [comment]
I spent an hour and managed to get through about 7 rows. The most consistent issue I had was 
a) trying to get access to a paper
b) trying to find accurate cell estimates for a paper (i would say about 40% of my time was specifically trying to find this) 

Here are the dcp_ids: 
dcp6567872905221278 
dcp6471713778515119 
dcp1128615412906442
dcp1572500052261878 
dcp2735614107786216
dcp2355289285407629
dcp6966279925931196

Out of the 7, 1 was unsuitable, 6 I set to 'acknowledged', none of them were hca_pubs.
Of the 6 suitable, 5 were open access, 1 was mixed.
1 was 'abnormal' tissue, 1 was 'normal', and 4 were 'both'.

**Comment by rays22** [comment]
I managed to curate **4 rows in 1 hour**.
1. and 2: Deleted 2 rows, because they contained no useful information. For example:
```
dcp4445935379681019         yes                                                                                                                          
```
3. Merged two rows, because they referred to the same primary data (E-MTAB-10026). It appears that the first of the two rows contained the pre-print information, and the second one the peer-reviewed paper. I have added the bibliographic information of the peer-reviewed paper to the row of the pre-print and also added a note in the [relevant ticket.](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/261) 
```
dcp3286277635403501                                                                                                 10.1038/s41591-021-01329-2                                     
```
4. Added `unsutiable` status to one row, because the primary data is not available publicly.
```
dcp4636338960847805         no      2020-11-12      human       not normal  Systemic sclerosis   Smart-seq2  Skin    184                 no  no    Single Cell RNA Sequencing Identifies HSPG2 and APLNR as Markers of Endothelial Cell Injury in Systemic Sclerosis Skin no  https://doi.org/10.3389/fimmu.2018.02191   30327649    10.3389/fimmu.2018.02191                SSc vs Healthy                      
```

**Comment by rays22** [comment]
* The median number of rows per person we managed to fill in during the 1 hour pilot is `2`.

```
25
7
4
0
0
0
```
