### ISSUE TITLE
address ops SOP comments

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#396]
These PRs have been open since early June.
Please address the review comments.
- [x] ebi-ait/hca-ebi-wrangler-central#346 Update AWS account creation SOP for contributors
- [x] ebi-ait/hca-ebi-wrangler-central#340 Add installation SOP for SCEA tools validators
- [x] ebi-ait/hca-ebi-dev-team#415 Rewrite the Delete project SOP's steps
