### ISSUE TITLE
Ensure the graph validator can be run on all data destined for DCP2

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-wrangler-central#4]
# Ensure the current experimental design validation tool can be run on all data destined for DCP2

The goal of this ticket is to make sure there is a process that ensures this validation from https://github.com/ebi-ait/ingest-graph-validator can be run on all datasets which are destined for DCP2

## Tasks

- [x] Decide within the wrangling team when in the data contribution process will this validation be run
- [x] If not everyone who needs to operate the validator has sufficient knowledge, run training on how run the validation
- [x] Collect feedback to enable planning for future iterations of the experimental design validator

## Acceptance criteria

- [x] There is a process in place to make sure this validator can be run on all datasets destined for DCP2
- [x] Everyone is able to propose new rules for the validator
- [x] Improvement suggestions based on feedback are recorded in the ingest-validator milestone list and communicated to @clairerye (**note** these individual improvements don't need to be immediately prioritized and set as milestones but this document seems like the right place to capture this information) https://docs.google.com/document/d/1mqTKTUo4VjjMygnZpJZ4uzADFDc0tKDNhWVpQVNvi-Y/edit?ts=5eb91e23#

**Comment by lauraclarke** [comment]
@rays22 @ESapenaVentura this is something I want to see completed in the next sprint. Please let me know if anything is unclear

**Comment by lauraclarke** [comment]
@rays22 @ESapenaVentura I have updated this ticket to reflect @tburdett's comments yesterday. Again, please let me know if anything is unclear @clairerye

**Comment by tburdett** [comment]
Thanks @lauraclarke, good summary. 

I think we discussed two possible options (there may be others):

1. We run graph validation over spreadsheets as soon as they are received by wranglers. This lives "outside" of the automated workflow but might make the feedback loop tighter for fixing these sorts of errors in the spreadsheet
1. We run graph validation once spreadsheets have been entered into ingest, immediately prior to submission. This is the expected long term solution, but might need a little bit more work now to ensure we can track when this runs. It also incurs some cost of how to delete/recreate submissions that are invalid.

To elaborate on what I mentioned yesterday: we just need to weigh up the tradeoffs and make an (ideally quick) decision on this that we can review later if needs be. My gut says changing processes is harder than implementing a minimal solution to incorporate this into ingest, but that's not a very informed opinion.

**Comment by ESapenaVentura** [comment]
This task is related to this other one:

https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/14

About what @tburdett said, At the time of the demo I didn't know that projects were accessible through the API prior to hitting the "submit" button. That opens the door to validating at the same time as the other metadata, which is a nice touch.

Work on the training process is being done by @rays22 at the moment, and as a "quick" decision we've decided that I will be running the tool on every dataset for the moment while we prepare the training for other wranglers and begin implementating it into ingest.

**Comment by rays22** [comment]
My broad plan for the ingest-graph-validator training is as follows:
step 1:
Everybody gets a installed ingest-graph-validator on their local machine. We should make sure that everybody uses the same, most up-to-date version.
step 2.
Hands on demonstration with examples of
- running validation on a spreadsheet
- running validation using a submission UUID
- graph visualisation features
- how to add/request new validation rules.

**Comment by rays22** [comment]
### ingest-graph-validator practical training notes  

* cypher snippets, useful commands and links
<https://docs.google.com/document/d/1lTvY7U02AT6uLe1pcvFTkt3GYfTP0JY8VJS-EBOSRaU/edit>

### How to request/propose new rules for the validator?

<https://github.com/ebi-ait/ingest-graph-validator/blob/master/graph_test_set/README.md>

**Comment by rays22** [comment]
We can collect feedback for improvements and add more documentation at an appropriate location/wiki if that proves necessary, but I think we can already run the graph validator on all data destined to DCP2.
