### ISSUE TITLE
Discussion: technical solutions for tracking datasets

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#43]
**Description of the task:**

As part of wrangling operations, we would like to improve the dataset tracking process by creating a software-focused solution. A set of problem statements and requirements for this has been written and reviewed. The next step in this ticket is to discuss a possible first iteration, basic technical solution(s) which can be implemented over 1 sprint and then reviewed in terms of how well it solves the problems identified.

Problems and Requirements Document: https://docs.google.com/document/d/1JHAwe1cG344VWxEBqXiUaWkz53ZNVQU1vvHOogIXvk0/edit

**Acceptance criteria:**

- [ ]  Create a draft of potential technical ideas pre-meeting

- [ ] Meeting to discuss technical ideas for 1st iteration

- [ ] Document a 1st iteration technical solution for review

**Comment by ami-day** [comment]
@gabsie would like to be involved in the discussion when we meet too

**Comment by lauraclarke** [comment]
@clairerye @ami-day is this meant to be in the sprint backlog?

**Comment by clairerye** [comment]
Nope, I think this can be closed and re-opened as a dev task when we are ready to work on implementing this.
