### ISSUE TITLE
Onboarding tasks for Irene Perez

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#468]
Welcome to the HCA DCP! We are pleased to introduce you to the data wrangling team. Before beginning to work by yourself, you'll be asked to complete a set of tasks and meetings. These will guide you through both the general and specifics of your role, and it will help us make sure you understand how we work in the team. You will perform these tasks on your own, but feel free to ask @ESapenaVentura if you have any question or query.

# Tasks

Your introductory tasks are:

- [x] Read the [onboarding document](https://ebi-ait.github.io/hca-ebi-wrangler-central/ebi-wrangler-onboarding.html).
- [x] Move this ticket from "to do" to "in progress" Pipeline in ZenHub.
- [x] Assign yourself to the ticket
- [x] Create an issue for each [general task](#general-tasks) and link them to this ticket.
- [x] Clone all the basic repos to your computer (look at the [onboarding document](https://ebi-ait.github.io/hca-ebi-wrangler-central/ebi-wrangler-onboarding.html) for more information)
- [x] Locate all the documents regarding SOPs. You don't need to read them for now, but make sure to know where they are (Via notes, bookmarking, etc)

## General tasks

These are wrangling-specific tasks. They will provide you with the basic knowledge necessary to perform your future tasks in the team. These include:
- [x]  Watch HCA Metadata Standard 101 [video](https://drive.google.com/open?id=12hGA3_ARTKl-W0JxMKm8fHqvx31L3Ohf) ([slides](https://drive.google.com/open?id=1CJZfFpVFPolYPf30NSNn3A4CPVHmbfbaHUKlzCqBz_c)).
- [x]  Familiarise yourself with the projects and Standard Operating Procedures (SOPs) inside the [hca-ebi-wrangler-central repository](https://github.com/ebi-ait/hca-ebi-wrangler-central/)
- [x]  Read up on FAIR Data Principles
    - [x]  [The FAIR Guiding Principles for scientific data management and stewardship (Wilkinson 2016)](https://www.nature.com/articles/sdata201618)
    - [x]  [A design framework and exemplar metrics for FAIRness (Wilkinson 2018)](https://www.nature.com/articles/sdata2018118)
    - [x]  [Quick summary](https://www.force11.org/group/fairgroup/fairprinciples) of FAIR Data Principles
    - [x] Also related: [Uniform resolution of compact identifiers for biomedical data (Wimalaratne 2018)](https://www.nature.com/articles/sdata201829)
- [x]  Add or update tickets in wrangling or metadata-schema repo to reflect work being done.
<These tasks are in the order they are meant to be introduced to the wrangler.>

## Specific role tasks

These tasks will give you an insight on your role, and provide you with the appropriate tools to proceed in your job. As your first dataset, you have been assigned to wrangle the HCA publication [Sampling time-dependent artifacts in single-cell genomics studies](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02032-0). To familiarise yourself to the wrangling process, your tasks regarding this dataset are:

- [x] Create a ticket in this repository using the `Published project tracker` template
- [x] Read the paper and gather the following information:
   - Type of tissue: primary, cell line, organoid?
   - Technology used for library preparation: 10x, smart-seq2?
   - Developmental stage of the donors: Adult, fetal, embryos?
- [x] Generate a spreadsheet. template from the [project page](https://contribute.data.humancellatlas.org/projects/detail?uuid=5b328561-4a97-40ac-b7ad-6a90fc59d374) in ingest. Try to use the information gathered from the previous point to generate it.
- [x] Create a google drive folder inside the [brokering](https://drive.google.com/drive/folders/118kh4wiHmn4Oz9n1-WZueaxm-8XuCMkA) folder and store the spreadsheet there
- [x] Read through the paper and try to fill the spreadsheet with the available information. Use the [spreadsheet quick guide](https://ebi-ait.github.io/hca-metadata-community/contributing/spreadsheet-guide.html) and this example dataset (WIP) to guide you through the process.
- [x] Once completed, post in the ticket that the dataset is ready for **secondary review** and tag @ESapenaVentura .
- [x] When secondary review is completed, you will have a meeting with @ESapenaVentura to go through the corrections/queries
- [ ] Follow the rest of the items in the ticket you created to finish the submission

# Onboard Meetings

These meetings will help you understand some aspects of the work here, as well as our work policy and important details about what technologies we use. They will be short (around 30 minutes) and you should try to get at least one per day. You will be expected to book the meeting with the person that is supposed to give it.

- [x] Introduction to agile: The manifesto and basic concepts. Project Manager (PM), Product Owner (PO), sprint, standup, tickets and story points. @amnonkhen 
- [x] Computational environments: DCP's Github workflow, recommended software (PyCharm, sublime, google sync, notes, postman). @ESapenaVentura 
- [x] Developmental environments: Development, Staging, Production. @Wkt8 
- [x] Metadata repository 1: Entities structure: core, type and module. Graphs as a tool to represent a project. @ESapenaVentura 
- [x] Metadata repository 2: Introduction to JSON, schema evolution and versioning. @ESapenaVentura 
- [x] Technologies: 10x, SMART-Seq2, Imaging transcriptomics, CITE-Seq, ATAC-Seq  @ami-day 
- [x] Wrangling repository: Tools, vignettes, tickets, MarkDown documents and processes. @Wkt8 
- [x] Spreadsheet generator: The spreadsheets and the contributor form. General tour of UI and how to generate one. @Wkt8 
- [x] Linked knowledge: Quick introduction to ontologies. @ami-day 
- [x] Components: DCP and organization. @gabsie 
- [x] Ingest component: Overview of ingest infrastructure. @aaclan-ebi @ESapenaVentura  

# Acceptance criteria

- [ ] Finish all the tasks outlined.
- [ ] Close this issue.
