### ISSUE TITLE
Integrate UCSC wrangled datasets into our tracker

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#59]
**Description of the task:**

Clay gave Laura a list of datasets that they have already wrangled. They are all GEO accessions and are listed here:

GSE118127
GSE102596
GSE109488
GSE100618
GSE130430
GSE89232
GSE97104
GSE86146
GSE114802
GSE83139
GSE73727
GSE117498
GSE108291
GSE120508
GSE70580
GSE100618
GSE130430 

**Acceptance criteria for the task:**

- [x] Check which datasets we already have in the tracker

- [ ] Add new datasets into the tracker sheet along with their key info.

- [ ] Update the datasets that we already have to show Complete status. Add a comment that indicates it was from UCSC.

**Comment by ami-day** [comment]
**Update:
 
We already have the following in our tracker:**

GSE108291
GSE120508
GSE70580
GSE100618
GSE130430
GSE102596
GSE100618
GSE130430
GSE89232
GSE83139
GSE73727

@Laura in turns out we already have quite a few of them, some of which were prioritised highly and acknowledged for wrangling so good to know. I noticed some of them were labelled 'unsuitable' due to bam format or only 1 fastq available. Do you know how they work with those kinds of datasets? We avoid them as we can't validate the data.

We don't have the following in our tracker and they will be added:**

GSE118127
GSE117498
GSE109488
GSE97104
GSE86146
GSE114802

**Comment by ami-day** [comment]
also @lauraclarke, how would you describe their status if wrangled by UCSC? there are various options in the tracker. We could potentially extend the drop-down to include 'complete - ucsc' but im wary in the future we will need to know exactly where they are and their state of completion (e.g. are they in ingest, ebi archives, etc.)

**Comment by lauraclarke** [comment]
So they will be tracking their own datasets in their own tracker. Once we have a software solution I think some sort of API driven exchange will be possible but for now I might be tempted to add a status that is UCSC wrangling and just leave it

**Comment by lauraclarke** [comment]
Quick question, when I did the accession search I didn't find most of those datasets, Any ideas why? I was using the vlookup system?

**Comment by ami-day** [comment]
Oh, that is weird. I was wondering why you weren't able to. I use the 'ctrl F' option on my Mac to search for key words anywhere in the sheet. I didn't try using vlookup

**Comment by ami-day** [comment]
*command F

**Comment by lauraclarke** [comment]
don't need to worry now, I might have a play to see if I can figure it out another time. Probably leading or trailing spaces or similar

**Comment by ami-day** [comment]
yea probbaly

**Comment by lauraclarke** [comment]
I wouldn't label them as complete, we don't know they are complete

**Comment by ami-day** [comment]
Oh, I thought you said they were. OK I will just label with 'UCSC' then

**Comment by lauraclarke** [comment]
I thought complete was has made it to archives and/or DCP, they definitely haven't done that

**Comment by ami-day** [comment]
Right ok. There are various ' Complete' options now in the drop-down list. But anyway, I have just labelled it as 'UCSC' now. The prioritisation number is still 8 which I think is ok, as essentially 8 just means it will be prioritised very low by our team.

**Comment by ami-day** [comment]
This is done now so Im closing the ticket.
