### ISSUE TITLE
Assemble a list of new data which can be submitted to DCP2 MVP release

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-wrangler-central#6]
# A list of new data which can be submitted to DCP2 MVP release from contributors and AE/GEO

The goal of this ticket is to understand and plan the transfer of data we have collected and curated from contributors and GEO/ArrayExpress since the DCP went into maintenance mode.

In rough order of importance, we need to assess

- What new contributions we have received since the start of December and have in a holding pattern or have submitted to the EMBL-EBI archives
- What data we have curated already from GEO and ArrayExpress
- What data we need to curate from the HCA publication list https://www.humancellatlas.org/publications/
- What data is in ArrayExpress that we should import #9 
- What additional data in GEO and the data tracking sheet should be curated? 

## Questions

The first question is how many datasets to we want to aim to get into DCP2. @lauraclarke has a gut feeling for this goal but would like to hear other people's views

Once we know all the datasets we are targetted we need to know:

If we have already wrangled it:

1. Where is the metadata? is it already submitted to ingest and valid both on schema and experimental design principles?
2. Where are the data files?

If we haven't started with the dataset yet:

1. Where is the metadata located?
2. Are the data files publicly accessible?

We should confirm what we already have in hand and then start on new dataset curation.
Datasets in the HCA publication list that have publicly accessible data should be prioritized over datasets that are not in that list.

An approximate list size of 20-30 datasets is a good goal to aim for.

We need to answer the following questions:

For data we have already curated
- [ ] How many datasets of this type do we have?
- [ ] How many are new contributions?
- [ ] How many are from ArrayExpress and GEO?
- [ ] Have all existing datasets have been submitted to ingest and have valid metadata
- [ ] Are all existing datasets are valid with respect tests run by the experimental graph validator

For data we have yet to curate
- [ ] How many HCA publications do we already have?
- [ ] How many HCA publications have public sequencing data and we can curate?
- [ ] Which HCA publications do we need to reach out to the authors about?
- [ ] Do we have a backlog of at least 30 datasets from the HCA publication list, ArrayExpress and GEO to start curation?

Each new dataset/publication we aim to send to DCP2 should have its own ticket which covers

## Ticket info
What is the publication?
Where is the data now?
What accessions are associated with the data
Where is the metadata
What steps are needed to get the data into HCA ingest if not already present

**Comment by mshadbolt** [comment]
should potentially review rejected datasets and potential datasets yaml to see if anything needs to be added to the tracker.

The completion of this epic hinges on everything being the spreadsheet tracker and our ability to filter and facet to answer the questions above.

**Comment by lauraclarke** [comment]
I would advise being exhaustive for the HCA publications and the potential dataset yaml but I would worry less about being exhaustive with AE and GEO as they are going to be very long list which we will need to periodically reasess.

**Comment by ami-day** [comment]
Update:

The below questions have been answered by the list of information located here:
https://docs.google.com/spreadsheets/d/1DfRFfZpZEmWU6aubKwIZ4D0lfm038IW0fmHRigS8yBU/edit#gid=552473761

- What new contributions we have received since the start of December and have in a holding pattern or have submitted to the EMBL-EBI archives? - **Done**

- What data we have curated already from GEO and ArrayExpress - GEO Done, awaiting ArrayExpress

- What data we need to curate from the HCA publication list -https://www.humancellatlas.org/publications/ - **Done**

- What data is in ArrayExpress that we should import #9 - **awaiting**

- What additional data in GEO and the data tracking sheet should be curated? - **Done**

**Comment by lauraclarke** [comment]
I can see what is done and could potentially be exported tomorrow from that list and what we have started? I can't tell what potential GEO datasets there are that we could wrangle between now and when the MVP data snapshot is declared?

Also, any chance for full project titles/publication links. The short names are useful for internal references, terrible for communicating to anyone else what these datasets are

**Comment by lauraclarke** [comment]
Also where are the HCA publications that we haven't curated in this list?

**Comment by ami-day** [comment]
> I can't tell what potential GEO datasets there are that we could wrangle between now and when the MVP data snapshot is declared?

Ah I didn't see this in the task description. Yes I could include this. Anything in the 'maybe' tab is in-progress, and there are many acknowledged GEO datasets in the tracker which have not been started. When would the MVP data snapshot be declared? will we have time to start converting new datasets?

**Comment by ami-day** [comment]
> Also where are the HCA publications that we haven't curated in this list?

There aren't any that aren't blocked or unsuitable. There was 1, but I had already converted it to HCA so it's already in the list (I didn't notice it was an HCA publication at the time)

**Comment by ami-day** [comment]
> Also, any chance for full project titles/publication links.

Yes, I'll add them

**Comment by lauraclarke** [comment]
> > Also where are the HCA publications that we haven't curated in this list?
> 
> There aren't any that aren't blocked or unsuitable. There was 1, but I had already converted it to HCA so it's already in the list (I didn't notice it was an HCA publication at the time)

If would be good to know what the top 30ish data sets between GEO and AE that we are targetted are. Then we can give people an insight into what's on our hitlist. Happy to extract that info from the tracker rather than having an independent sheet but I don't know how to do that

**Comment by ami-day** [comment]
> If would be good to know what the top 30ish data sets between GEO and AE that we are targetted are.

Do you mean, you would like a list of 30ish NEW datasets that have NOT been converted and that are available in GEO and AE that we can start curating for DCP2.0? I am confused because I have been focusing on listing which datasets have been completed or are almost complete.

**Comment by ami-day** [comment]
I will add a list of high priority 'to do' GEO datasets to the file now, which I have already assessed as suitable and high priority

**Comment by ami-day** [comment]
(this task is keeping me motivated to help get a software tracking solution up and running!!)

**Comment by lauraclarke** [comment]
These questions from the ticket are intended to be prospective 

What data we need to curate from the HCA publication list
What additional data in GEO and the data tracking sheet should be curated?  
What data is in ArrayExpress that we should import 

So the goal was to understand what new data we wanted to prioritize as well as what we had already done

**Comment by ami-day** [comment]
Ok, so I have added the following to the maybe tab:

- List of datasets which are in-progress (contributors & GEO)
- List of high priority datasets which we need to curate from GEO
- No suitable data is available from the HCA publication list

So far there are 23 datasets in this list. Information about data in ArrayExpress which we should import is being assessed by @rays22

**Comment by rays22** [comment]
> What data is in ArrayExpress that we should import

All the AE candidate datasets are already in the [Dataset Tracking Sheet](https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/edit#gid=0) with wrangling status and priority flags.
I think 5 + 2 + 4 + 1 datasets would be high priority for uploading to DCP 2, but others with lower priorities could be targeted too.
<https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/9#issuecomment-630945605>

**Comment by rays22** [comment]
I have added a few new datasets to the table [Datasets for DCP2.0 MVP](https://docs.google.com/spreadsheets/d/1lJFPR-loZuBhKdijOcSOn7wqe_-N4MYWKJkLFfRqefU/). <https://docs.google.com/spreadsheets/d/1lJFPR-loZuBhKdijOcSOn7wqe_-N4MYWKJkLFfRqefU/>
I was not sure into which section to put the datasets that have been archived and have passed HCA spreadsheet metadata validation. I think they are closer to `Complete` than to `Maybe`, so I added them to the `Complete` section.



> What data we need to curate from the HCA publication list

There is a publication from the HCA publication list that has author overlap and a very similar title to an ArrayExpress dataset `E-MTAB-8498 - Human dendritic cell subsets in acute skin inflammation`. It is already on the Dataset Tracking Sheet. Smart-Seq2 protocol.

Chen, Yi-Ling; Gomes, Tomas; Hardman, Clare S; Vieira Braga, Felipe A; Gutowska-Owsiak, Danuta; Salimi, Maryam; Gray, Nicki; Duncan, David A; Reynolds, Gary; Johnson, David; Salio, Mariolina; Cerundolo, Vincenzo; Barlow, Jillian L; McKenzie, Andrew N J; Teichmann, Sarah A; Haniffa, Muzlifah; Ogg, Graham 2020    3   Re-evaluation of human BDCA-2+ DC during acute sterile skin inflammation.   J Exp Med
31845972        10.1084/jem.20190811

**Comment by lauraclarke** [comment]
It is essential that we can differentiate between datasets that have made it to archives and datasets which have made it to DCP.

What is the best way to track this difference? @ami-day any ideas? anyone else?

**Comment by ami-day** [comment]
> It is essential that we can differentiate between datasets that have made it to archives and datasets which have made it to DCP.
> 
> What is the best way to track this difference? @ami-day any ideas? anyone else?

I think the best way would be to identify and compare the list of biosample accessions (SAMN...) or experiment accessions (SRX....). Specifically, if they are all identical and if any are missing from either publication compared to the other. These accessions are what I believe would be most stable and consistent. I might be wrong about that though?

**Comment by ami-day** [comment]
> so I added them to the `Complete` section.

I agree @rays22 I have added datasets with this status to the 'Complete' section and indicated in the 'where are they stored' column that they are in HCA ingest - archiving. It might be worth adding whether that is staging or production, if you have that information.

**Comment by lauraclarke** [comment]
> > It is essential that we can differentiate between datasets that have made it to archives and datasets which have made it to DCP.
> > What is the best way to track this difference? @ami-day any ideas? anyone else?
> 
> I think the best way would be to identify and compare the list of biosample accessions (SAMN...) or experiment accessions (SRX....). Specifically, if they are all identical and if any are missing from either publication compared to the other. These accessions are what I believe would be most stable and consistent. I might be wrong about that though?

I need to be able to answer that question using only the spreadsheet.

**Comment by lauraclarke** [comment]
> > so I added them to the `Complete` section.
> 
> I agree @rays22 I have added datasets with this status to the 'Complete' section and indicated in the 'where are they stored' column that they are in HCA ingest - archiving. It might be worth adding whether that is staging or production, if you have that information.

Projects/Publications which started in GEO or AE and haven't yet made it to the DCP are not complete

**Comment by ami-day** [comment]
In the HCA status column there is the option to select 'Complete - in DCP' or 'Complete - in other EBI archive' , can you use that? There is also the option 'Complete - in AE' in the 'SCEA status' column. BUT I would say this information has not been reliably entered because we only realised we needed to modify the drop-down lists fairly recently. These distinctions were not in the original version. Therefore, finding this information inevitably requires some work unfortunately because it was never added in the first place. Saying that, you could also filter by accession id for any accessions that have "MTAB" in the id, that would probably be the most reliable way to do it.

**Comment by ami-day** [comment]
It will be clear from the way that I have stored information in the above file I pasted a link to which datasets started in GEO or AE and are not in the DCP. Anything that is not labelled 'in DCP' is not already in the DCP.

**Comment by rays22** [comment]
> > > so I added them to the `Complete` section.
> > 
> > 
> > I agree @rays22 I have added datasets with this status to the 'Complete' section and indicated in the 'where are they stored' column that they are in HCA ingest - archiving. It might be worth adding whether that is staging or production, if you have that information.
> 
> Projects/Publications which started in GEO or AE and haven't yet made it to the DCP are not complete

OK, that is clear now. I will move the datasets that are not in DCP to the `Maybe` section.

**Comment by rays22** [comment]
> In the HCA status column there is the option to select 'Complete - in DCP' or 'Complete - in other EBI archive' , can you use that? There is also the option 'Complete - in AE' in the 'SCEA status' column. BUT I would say this information has not been reliably entered because we only realised we needed to modify the drop-down lists fairly recently. These distinctions were not in the original version. Therefore, finding this information inevitably requires some work unfortunately because it was never added in the first place. Saying that, you could also filter by accession id for any accessions that have "MTAB" in the id, that would probably be the most reliable way to do it.

@ami-day ,
If I/we make a new column for EBI archiving status in the Dataset Tracking Sheet, and use the HCA status column exclusively for DCP status (e.g. Complete - in DCP), and the new `EBI archiving status` for exclusively the archiving status (e.g. Complete - in EBI archive), would that help answer the question that @lauraclarke has about differentiating the two? It would involve some editing of the spreadsheet.

**Comment by rays22** [comment]
> > so I added them to the `Complete` section.
> 
> I agree @rays22 I have added datasets with this status to the 'Complete' section and indicated in the 'where are they stored' column that they are in HCA ingest - archiving. It might be worth adding whether that is staging or production, if you have that information.

@ami-day 
OK, I am going to collect that information.

**Comment by ami-day** [comment]
@lauraclarke I think this is done now, especially with Marion's update to the tracker directly. Can we close it?
