### ISSUE TITLE
Run the ingest-graph-validator on these large DCP1 datasets

### ISSUE THREAD

**Issue by rays22** [ebi-ait/hca-ebi-wrangler-central#69]
**Description of the task:**

AUDR	Project short name	Ingest submission UUID	Project name
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/312>	1M Neurons	064d36ca-ea4d-428f-b30f-0cf5e5350a9d	1.3 Million Brain Cells from E18 Mice
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/316>	Tabula Muris	14df1f92-155c-4da2-97fc-85601dee64da	Tabula Muris: Transcriptomic characterization of 20 organs and tissues from Mus musculus at single cell resolution
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/358>	Mouse Melanoma	4756b97c-3666-4ff0-9c48-611dc06b7740	Melanoma infiltration of stromal and immune cells
- [ ] non-DCP1 dataset?:	Single-cell transcriptional landscape of human embryonic limb development

**Acceptance criteria for the task:**

- [ ] All datasets have gone through cross-entity validation.
- [ ] Any identified errors are added to the relevant AUDR or tracking tickets as comments.
