### ISSUE TITLE
Fix the cross-entity errors in DCP1 datasets uncovered by the ingest-graph-validator

### ISSUE THREAD

**Issue by rays22** [ebi-ait/hca-ebi-wrangler-central#70]
**Description of the task:**

- [ ] Check AUDR ticket comments for cross-validation errors
- [ ] Fix any valid cross-entity errors identified by the ingest-graph-validator. 

**Acceptance criteria for the task:**

Datasets pass cross-entity validation by the <https://github.com/ebi-ait/ingest-graph-validator/tree/master/graph_test_set>

AUDR	Project short name	Ingest submission UUID	Project name	Note
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/177>	Fetal/Maternal Interface	46fe8bd7-329b-4f09-b227-5ee48c109c16	Reconstructing the human first trimester fetal-maternal interface using single cell transcriptomics		
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/349>	Single cell RNAseq characterization of cell types produced over time in an in vitro model of human inhibitory interneuron differentiation	0948a727-228f-4cfc-857e-6243c6aed08d	Single-cell RNA-seq analysis throughout a 125-day differentiation protocol that converted H1 human embryonic stem cells to a variety of ventrally-derived cell types.		
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/350>	Single cell transcriptome analysis of human pancreas	5cd8b827-e4fa-4ffa-86f5-f0f8302baee9	Single cell transcriptome analysis of human pancreas reveals transcriptional signatures of aging and somatic mutation patterns.		
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/354>	Human Hematopoietic Profiling	7dbcf5ae-f8d7-487c-a3d4-794d8639a1e2	Profiling of CD34+ cells from human bone marrow to understand hematopoiesis		
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/357>	HPSI human cerebral organoids	fce97270-fce0-4744-8a4e-a93d95521852	Assessing the relevance of organoids to model inter-individual variation		
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/362>	Multiplexed scRNA-seq with barcoded antibodies	6931d821-9cd2-4ae1-acf7-62cd3b90082e	Cell hashing with barcoded antibodies enables multiplexing and doublet detection for single cell genomics		
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/368>	WongAdultRetina	668791ed-deec-4470-b23a-9b80fd133e1c	A single-cell transcriptome atlas of the adult human retina		
- [ ] ?>	scFetalPaedIBDGut	dca729d5-e66c-476b-a646-632c4499820b	Single-cell sequencing of developing human gut reveals transcriptional links to childhood Crohn’s disease		
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/236>	HumanMousePancreas	7b4cd093-bfa5-477e-9c95-69bafc1cb6bf	A Single-Cell Transcriptomic Map of the Human and Mouse Pancreas Reveals Inter- and Intra-cell Population Structure	contains_cell_barcode_info.adoc; contains_umi_barcode_info.adoc 	
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/271>	MouseGastrulationAtlas	19c5c89a-7bfb-4b4d-9ff5-3ef009304ba5	A single-cell molecular map of mouse gastrulation and early organogenesis	no_orphans.adoc	
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/313>	snRNA-seq_for_human_retina	7d515499-b5b6-4083-95cd-6a393344865e	Transcriptomic classification of human retinal cell types with single-nuclei RNA-seq.	10x_has_more_than_2_files.adoc; ensure_lane_index.adoc	
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/329>	scRNAseqSystemicComparison	d1610c4a-76c6-4b69-af63-c74af869fa75	Systematic comparative analysis of single cell RNA-sequencing methods	10x_has_more_than_2_files.adoc	
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/331>	Diabetic Nephropathy snRNA-seq	a69c731b-9db7-45e3-938f-daf2e4636a6e	The Single Cell Transcriptomic Landscape of Early Human Diabetic Nephropathy	10x_has_more_than_2_files.adoc	
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/341>	KidneySingleCellAtlas	702313be-fdde-42ea-89a5-bd1b01531736	Spatio-temporal immune zonation of the human kidney	imported 0 nodes; 0 edges	
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/341>	KidneySingleCellAtlas	9cfca427-6e22-447a-867e-4d81fdb7391c	Spatio-temporal immune zonation of the human kidney	imported 0 edges	
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/341>	KidneySingleCellAtlas	d5410c6e-612d-421a-a66f-2de5e04dd050	Spatio-temporal immune zonation of the human kidney	protocol_document_has_supplementary_file.adoc	
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/341>	KidneySingleCellAtlas	2afc1a93-f35d-4dec-95b7-7bd54b6da834	Spatio-temporal immune zonation of the human kidney	imported 0 nodes; 0 edges	
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/341>	KidneySingleCellAtlas	9e1d7bdc-e4a8-4dac-a131-6434aeb15bd0	Spatio-temporal immune zonation of the human kidney	imported 0 nodes; 0 edges	
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/351>	BM_PC	67abd7a1-644b-48d0-b8b8-251d8195a742	Bone marrow plasma cells from hip replacement surgeries	contains_umi_barcode_info.adoc; protocol_document_has_supplementary_file.adoc 	
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/352>	Kidney biopsy scRNA-seq	588281cb-93e2-4888-b75e-5cee5e39fc7f	Single Cell Transcriptomics of a Human Kidney Allograft Biopsy Defines a Diverse Inflammatory Response	protocol_document_has_supplementary_file.adoc	
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/353>	HumanColonicMesenchymeIBD HumanColonicMesenchymeIBD	c51efa69-a348-46d4-9997-c7a11915d53b	Structural Remodeling of the Human Colonic Mesenchyme in Inflammatory Bowel Disease	no_orphans.adoc	
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/353>	HumanColonicMesenchymeIBD HumanColonicMesenchymeIBD	8d2aace1-34d6-4c6c-bc4a-3af461dd7559	Structural Remodeling of the Human Colonic Mesenchyme in Inflammatory Bowel Disease	contains_cell_barcode_info.adoc; contains_umi_barcode_info.adoc; 10x_has_more_than_2_files.adoc	
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/356>	1M Immune Cells	85e72912-9f91-4489-8169-3b43cc65a16a	Census of Immune Cells	10x_has_more_than_2_files.adoc	
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/359>	Healthy and type 2 diabetes pancreas	c81f7d54-a27f-4212-a6df-88dde947f7cc	Single-cell RNA-seq analysis of human pancreas from healthy individuals and type 2 diabetes patients	10x_has_more_than_2_files.adoc; smartseq2_has_2-3_files.adoc; paired_end_2_files.adoc	
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/360>	Drop-seq, DroNc-seq, Fluidigm C1 Comparison	bf3116e5-1af1-46c2-8bbd-44dac49d1e7f	Comparison, calibration, and benchmarking of high-throughput single cell RNA-Seq techniques for unbiased cell-type classification	contains_umi_barcode_info.adoc	
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/361>	CD4+ cytotoxic T lymphocytes	3bb965cb-2a6f-4802-a4f2-52d0423e6ecc	Precursors of human CD4+ cytotoxic T lymphocytes identified by single-cell transcriptome analysis	smartseq2_has_2-3_files.adoc; paired_end_2_files.adoc	
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/363>	SingleCellLiverLandscape	1e2601a5-8938-446c-bbb3-1f37a84b11da	Dissecting the human liver cellular landscape by single cell RNA-seq reveals novel intrahepatic monocyte/ macrophage populations	10x_has_more_than_2_files.adoc	10x_has_3-4_files.adoc
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/365>	Mouse Endoderm Project	0fb44736-c50f-49ab-bcdc-0985e596b955	The emergent landscape of the mouse gut endoderm at single-cell resolution	10x_has_more_than_2_files.adoc	10x_has_3-4_files.adoc
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/366>	Reprogrammed_Dendritic_Cells	4f590376-7a5e-4bdc-9ae0-a0eb16602513	Single cell profiling of human induced dendritic cells generated by direct reprogramming of embryonic fibroblasts	imported 0 edges	imported 0 edges
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/366>	Reprogrammed_Dendritic_Cells	5c438071-abc3-4b34-8f55-d90bfe29c404	Single cell profiling of human induced dendritic cells generated by direct reprogramming of embryonic fibroblasts	no_orphans.adoc; 10x_has_more_than_2_files.adoc	10x_has_3-4_files.adoc
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/366>	Reprogrammed_Dendritic_Cells	8c45a848-ab32-4928-8dd6-567b75eaf7e1	Single cell profiling of human induced dendritic cells generated by direct reprogramming of embryonic fibroblasts	imported 0 edges	imported 0 edges
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/367>	HumanTissueTcellActivation	8b5feb5e-9039-4c54-9e79-053e490c141a	A single-cell reference map of transcriptional states for human blood and tissue T cell activation	imported 0 edges	imported 0 edges
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/367>	HumanTissueTcellActivation	cad1dcdd-f49a-4f9c-9417-359b0e5bdd12	A single-cell reference map of transcriptional states for human blood and tissue T cell activation	ensure_seq_libr_prep_protocols.adoc	10x_has_3-4_files.adoc
- [ ] <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/355>; <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/370>	TissueSensitivity	fd52efcc-6924-4c8a-b68c-a299aea1d80f	Ischaemic sensitivity of human tissue by single cell RNA seq	sequence_file_linkto_cell_suspesion.adoc; min_experimental_design_length_5.adoc; contains_cell_barcode_info.adoc; contains_umi_barcode_info.adoc; protocol_document_has_supplementary_file.adoc	
- [ ] non-DCP1 dataset>	AdultHemOrgans	7a24654c-1b54-497e-82b7-c793ede4a02f	Transcriptomic characterisation of haematopoietic stem and progenitor cells from human adult bone marrow, spleen and peripheral blood	10x_has_more_than_2_files.adoc; ensure_lane_index.adoc
