### ISSUE TITLE
Define the scope of updates in the DCP2 MVP

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-wrangler-central#71]
# Goal

## User stories

1. As a data contributor, I want to add additional information about my samples and experiments to my contribution
2. As a data contributor, I want to fix errors in the information I provided about my samples and experiments
3. As a data consumer, I want to be confident in the accuracy of the metadata associated with HCA data in the DCP

### Existing functionality
1. What classes of updates can the ingest importer and core infrastructure already support
2. What work is involved in ensuring the exporter what are the requirements for downstream DCP services to support these classes of updates
3. What is the cost of that making the exporter and downstream services supporting these classes of updates and how does it impact the DCP delivery timelines?
4. How many of the DCP1 dataset updates can be supported by these classes of updates https://docs.google.com/spreadsheets/d/1B52QjioJ7CzOLXFIcB-Q8mfjiFSH0jzbfdNs_nce3P4/edit#gid=1663653290
5. Have all the errors identified in the experimental design validation been added to the above list and do any of them fall into these classes of updates

### New update features

1.  What classes of updates do we not support currently?
2. What value to data consumers does delivering these classes of updates provide?
3. What is the cost of implementing these classes to ingest
4. What requirements would supporting these classes of updates have for the TDR teams or the Data Browser team?
5. If we were to implement any of these classes of updates, how would that implementation impact the timeline for delivery of MVP

### New data not in DCP1

1. Have we identified any updates for new datasets which aren't in DCP1?
2. Where are those updates recorded?

### How this impacts pipelines

1. Do any of the updates we plan to do require pipelines to be rerun with different settings?

### Other questions

1. Can we/should we include the INSDC study/project id switch as part of this effort? 
2. Can we/should we include review/update of schema regexes as part of this effort?
3. Does the scope of this effort suggest we need to relax the view that no scientific/user supplied schema changes should be allowed for MVP
4. Do any in-scope updates require us to develop a schema migration solution for ingest during MVP phase
5. What process is envisioned to propagate these updates through various pipes for DCP2 MVP release?

An outcome that updates are not possible for MVP is acceptable but we would need to understand why and what the consequences for both contributors and consumers for not making these updates

## Acceptance criteria

- [ ] Scope definition for (meta)data updates in DCP2 MVP
- [ ] Definition of new features that need to be implemented to meet the defined scope
- [ ] List of updates which can be propagated and a timeline for those updates
- [ ] Confirmation from TDR import team they are happy with a defined scope and understand the consequences for their own development plans
- [ ] Confirmation from Data browser team they are happy with the defined scope and understand the consequences for their own development plans
- [ ] Confirmation from pipelines team they are happy with the defined scope and understand the consequences for their own development plans

### Future context
We will want to reflect these updates in the archives too so that the archive version and DCP2 version are the same. This is not urgent, but will need to be done at some point.

**Comment by lauraclarke** [comment]
So I think when in my original statement I said we would like to be able to add new fields to the schema no one had pointed out that our no additional attributes design choice (which I support) would mean even new optional fields still require migration of old data to the new schema.

@rolando-ebi @mshadbolt @ESapenaVentura can you comment here? Is there any way to legitimately add new optional fields to our existing schema without having a migration strategy?

**Comment by lauraclarke** [comment]
Old ticket contents 
We need to decide the scope of updates that are realistic for pushing to DCP2 for the MVP.
As I understand it, @lauraclarke please comment/correct, there will be no schema updates for the MVP that reflect scientific changes. However this does still allow for the addition of new optional fields, if they are outside of the CORE of the schema and therefore do not require migrating of datasets.
From the work on AUDR and the work establishing the updates required https://docs.google.com/spreadsheets/d/1B52QjioJ7CzOLXFIcB-Q8mfjiFSH0jzbfdNs_nce3P4/edit#gid=1663653290 we need to assess what changes to ingest are worth making at this point to be able to update the biggest and most common mistakes in the DCP1 data.
As migration/ breaking schema changes are not currently in scope for the MVP. Do we have updates we need to make that mean we should:

Push for breaking schema change and migration, to allow for all datasets to be updated as needed
Some schema changes and re-ingestion of affected datasets, to allow for some/most datasets to be updated
Some schema changes and adaption of ingestion to allow the addition of new metadata fields
No updates to datasets requiring schema changes until post MVP
There are various trade-offs with each of these options and it is important to understand the implications of each. The aim of this ticket is to present the pros and cons of each of the above options (and other options, which might be better) along with a proposal of which is the preferred option for discussion.
We need to let UCSC/Broad know asap any datasets where the updates will affect pipelines. And any plans for re-ingestion or other plans that are likely to affect them.

**Comment by mshadbolt** [comment]
Tagging myself on this ticket to make some task tickets to put in the sprint backlog for myself

**Comment by mshadbolt** [comment]
Not sure who wrote them but can either @clairerye or @lauraclarke clarify some of the questions above

## Existing functionality
Question 1 - do you mean whether we can do the update within ingest rather than whether we can propagate that update downstream to other components?
Question 2 doesn't make sense, not sure if it needs to be split into two questions or what it is actually getting at
Question 3 - still a bit confused on this as we have been told that analysis will be doing a manual check to see that pipelines run correctly?
Question 4 - The cost of what work?

## New update features
Question 3 - do you mean the cost of implementing all possible classes of updates into ingest?

**Comment by mshadbolt** [comment]
@ESapenaVentura @rays22 I believe you both did work on running datasets through the experimental graph validator (#14 ), were you recording any errors in the spreadsheet linked above  in question 6 of 'Existing functionality'

**Comment by rays22** [comment]
> @ESapenaVentura @rays22 I believe you both did work on running datasets through the experimental graph validator (#14 ), were you recording any errors in the spreadsheet linked above in question 6 of 'Existing functionality'

I have not recorded any errors in the spreadsheet <https://docs.google.com/spreadsheets/d/1B52QjioJ7CzOLXFIcB-Q8mfjiFSH0jzbfdNs_nce3P4/edit#gid=1663653290> .

I have recorded the cross-entity validation errors in the relevant AUDR tickets and 
<https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/70> .

**Comment by clairerye** [comment]
good questions @mshadbolt I will try to answer, but maybe best if @lauraclarke also comments.

> Question 1 - do you mean whether we can do the update within ingest rather than whether we can propagate that update downstream to other components?
This Possibly needs to be 2 or 3 questions
1. Can we do the updates in ingest?
2. Can we get the updated submission to the GCP? - Not looking at archives yet.
3. Can anyone downstream do anything with the updated submission after its in the GCP?

> Question 2 doesn't make sense, not sure if it needs to be split into two questions or what it is actually getting at
I think this is actually asking point 2 and 3 above.

> Question 3 - still a bit confused on this as we have been told that analysis will be doing a manual check to see that pipelines run correctly?
In that case, perhaps its more of letting them know the decision we make rather than trying to include this initially.

> Question 4 - The cost of what work?
How much effort will it take to implement updates in ingest (if not possible) and get the updated submissions to GCP (if not possible).
I think downstream costs should also be considered, but separately to our own.

**Comment by lauraclarke** [comment]
Okay to add some clarification given I wrote the questions

1. What classes of updates can the ingest importer and core infrastructure already support

Ie, if a wrangler was to try and resubmit an already ingested spreadsheet with some changes to the metadata, what type of updates would be applied to ingests existing records about a dataset and what type of updates would cause ingest to either barf or make a mess of our internal records?

2. What work is involved in ensuring the exporter what are the requirements for downstream DCP services to support these updates

This is about once the ingest database contains the updated metadata (or data), what changes are needed in the exporter and what if any changes are needed in the Terra importer or other downstream services so those updates are also propagated to these other services

3. Do any of the updates impact how analysis pipelines run?

This is actually an independent question from the other two and I possibly shouldn't have put it in the same list. This question is getting at if updates we can do would need pipelines to be retriggered because then we have to figure out the right way to communicate those changes and inform the pipelines time of when they should or shouldn't run those pipelines (they might want to avoid running at all in the first instance given it is all manual if an update is coming they would require them to rerun)

4. What is the cost of that work and how does it impact the DCP delivery timelines?

I should have been specific to that, I meant any changes we need to make to the exporter and any changes anyone else needs to make to downstream services

**Comment by lauraclarke** [comment]
And for 

##  New update features

1. What classes of updates do we not support currently?
2. What value to data consumers does delivering these updates provide?
3. What is the cost of implementing the functionality to ingest

question 3 refers to any new class of update that we want to implement so we can decide if the value scientists will get during the MVP for supporting this type of update is worth the effort involves so perhaps it should be updated with "For each class of update"

This does need to be considered by both us and downstream components as updates can't just stop at the ingest importer

**Comment by mshadbolt** [comment]
I have started on a document here: https://docs.google.com/document/d/11x8RDBmB2un1RTAXF3HKgcx-uUBD-Bkrl3QycrcnHc8/edit?usp=sharing
