### ISSUE TITLE
Submit all unarchived DCP1 projects to EMBL-EBI archives

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-wrangler-central#8]
The goal of this ticket is to ensure that any unarchived DCP1 datasets are submitted to the appropriate EMBL-EBI archives.

View of spreadsheet tracker with unarchived datasets in DCP:
https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/edit#gid=0&fvid=1615088206

Please note we only need to archive raw data. We do not need to archive any analysis results

## Questions to answer
- [x] Are there any extra DCP1 projects which need to be either partially or completely submitted to EMBL-EBI archives 
  *yes, these now have tickets in the backlog*
- [x] Have any of the DCP1 projects listed above been submitted to archives through a different process and we have not captured the archive accessions? 
  *Yes, I have added tasks to AUDR tickets*
- [x] Does the metadata associated with these projects exist in the current ingest production infrastructure?
  *Yes, the current infrastructure is a mirror of the DSS as it was at the point of maintenance mode for datasets already submitted to the DCP.*
- [x] Are any metadata updates required before we submit these projects to the EMBL-EBI archives?
  *Mostly no, as a lot of this work was completed for the r-release but I'd advise double checking AUDR tickets which are linked to each archive ticket*
- [x] How do we ensure any records in ingest infrastructure capture the correct document ids so updates can be propagated to DCP2
  *As specified above, existing projects uuids should be consistent in ingest infrastructure as with the DSS uuids so this shouldn't be an issue.*

An epic should be created to track all the DCP1 archiving and tickets should be created for each individual project that needs to be archive

The ticket should reflect

- Where is the most current metadata spreadsheet for this project?
- Where is the data? 
- Do any fastq files need conversion to BAM format
- Is the spreadsheet already in the HCA ingest system and does all the metadata between the spreadsheet and ingest 
- Does ingest contain the correct document ids which will enable subsequent updates in DCP2

**Acceptance criteria for the task:**

- [x] Tickets exist in the backlog for each DCP1 dataset that needs to be submitted to EMBL-EBI archive
- [x] An epic which captures all these tickets exist to track our progress to completion.
- [ ] All projects are archived

There is a link between this work and the work to update metadata errors in any datasets from DCP1 in DCP2
https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/5

**Comment by mshadbolt** [comment]
Will bug @ESapenaVentura as necessary

**Comment by zperova** [comment]
related ticket: https://github.com/HumanCellAtlas/hca-data-wrangling/issues/427

**Comment by mshadbolt** [comment]
@lauraclarke does this ticket require that raw data is archived? For example if the expression matrix data is archived in GEO would we still proceed with archiving the raw data in an EBI archive?

Also would it be important for those datasets that are already in the DCP but may not have associated archival ids for the metadata to be updated for the DCP2 MVP?

**Comment by mshadbolt** [comment]
also @lauraclarke  I don't understand this question "Does the metadata associated with these projects exist in the current ingest production infrastructure?"

I don't see how projects in DCP1 could not exist in the current ingest infrastructure?

**Comment by lauraclarke** [comment]
> @lauraclarke does this ticket require that raw data is archived? For example if the expression matrix data is archived in GEO would we still proceed with archiving the raw data in an EBI archive?

I would like to know how many datasets are in the situation and then we can discuss the best plan, if we should archive the fastq files or not

> Also would it be important for those datasets that are already in the DCP but may not have associated archival ids for the metadata to be updated for the DCP2 MVP?

Archive accessions should be added to DCP2 records

**Comment by lauraclarke** [comment]
> also @lauraclarke I don't understand this question "Does the metadata associated with these projects exist in the current ingest production infrastructure?"
> 
> I don't see how projects in DCP1 could not exist in the current ingest infrastructure?

This probably reflects my limited understanding of the ingest infrastructure. I am aware that we have moved ingest databases and ingested some datasets multiple times so I am not sure what the current state of plan

Maybe the better question is do the records in the current production ingest interface for these datasets match the document ids in the DSS? I think I asked that in the updates ticket but I can't recall.

**Comment by mshadbolt** [comment]
Below is a table that summarises projects that require some action in regard to archiving. 

There are 6 projects that require some form of actual archiving to be done

The rest need to have archiving metadata added to project metadata.

Next steps are to make tickets for those projects that require archiving action and add to AUDR tickets for those that require metadata updates.

HCA Project Short Name | Archival Accession ID | HCA status Comment
-- | -- | --
Multiplexed scRNA-seq with barcoded antibodies | GSE108313 | archival ids need to be added to metadata
Drop-seq,DroNc-seq,C1 comparison Basu May | GSE129096 | archival ids need to be added to metadata; publication needs to be added to metadata
snRNA-seq_for_human_retina |   | to be archived
Human Hematopoietic Profiling |   | ENA archiving needs to be done;archival ids need to be added to metadata
InVitroInterneuronDifferentiation | GSE93593 | archival ids at sample/file level need to be added to metadata
Mouse Melanoma | E-MTAB-7427;E-MTAB-7417 | archival ids at sample/file level need to be added to metadata
HumanTissueTcellActivation | GSE126030 | Archival ids need to be added to metadata
scRNAseqSystemicComparison | GSE132044 | archival ids need to be added at file/specimen level, other data to be added?
Mouse Endoderm Project | GSE123046;GSE123124 | archival ids need to be added at file/specimen level
Diabetic Nephropathy snRNA-seq | GSE131882 | archival ids need to be added at file/specimen level
BM_PC | GSE117156 | archival ids need to be added to metadata
1M Immune Cells |   | to be archived
KidneySingleCellAtlas |   | ENA archiving needs to be done;archival ids need to be added to metadata
Reprogrammed_Dendritic_Cells |   | ENA archiving needs to be done;archival ids need to be added to metadata
TissueStability | PRJEB31843 | In progress archiving; new archive ids will need to be added to the submission
WongAdultRetina | E-MTAB-7316 | archival ids need to be added to metadata

**Comment by mshadbolt** [comment]
I have converted this into an Epic and added the tickets for datasets that need some form of archiving to be completed.

I have added tasks to the existing AUDR tickets for projects that require archival accessions to be added to metadata. 

I believe all tasks requested by the original ticket for this sprint are complete.

**Comment by lauraclarke** [comment]
Great thanks for sorting this all out @mshadbolt 

@clairerye @justincc Can you post here when you think the system is ready for this archiving to proceed if that is true before the end of this sprint. Otherwise, we should prioritize these tickets for the following sprints.
