### ISSUE TITLE
SingleCellsAlzheimers stuck in exporting

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#825]
The [submission for SingleCellsAlzheimers](https://contribute.data.humancellatlas.org/submissions/detail?uuid=02091ded-75b6-47e8-8967-9a625482c3c2&project=b51f49b4-0d2e-4cbd-bbd5-04cd171fc2fa) is stuck in _Exporting_.

**History**

1. The metadata for the cell suspensions has been updated to reflect new cell counts that have been requested by a contributor.
2. The update was done through spreadsheet.
3. After metadata re-validation, and graph re-validation, the "submit" button was hit with the checkbox "Export only metadata" checked.
4. Since then it has been in "exporting" status.

**Tasks**

- [x] Investigate if all the needed entities have been exported
- [x] this is on @ami-day , if the previous point is alright then submit an import form
- [x] Investigate why this dataset got stuck in exporting
- [ ] Write out conclusions of the investigation and follow ups (tickets, PRs, etc)

**Links**
- dataset ticket

**Comment by gabsie** [comment]
@ESapenaVentura to see this as well.

**Comment by ESapenaVentura** [comment]
This has been done - Set the cell suspension cell count to 1 for the ss2 samples, 25k for 10X samples. submission is exporting, only work needed is to monitor and fill out the import form

**Comment by gabsie** [comment]
Awesome, thanks, @ESapenaVentura !

**Comment by ESapenaVentura** [comment]
Submission stuck in exporting - Needs investigation

**Comment by ofanobilbao** [comment]
If this is really still being investigated, and not resolved (I can see the project still is Exporting in Ingest) why is there already an Import form for this project? We should not be filling it in advance right?

**Comment by ESapenaVentura** [comment]
@ofanobilbao the project was exported, as far as I know. The only problem I see is the status, but I checked the staging area and the entities of interest (the cell suspensions) were there.

I would say to not take my statement with 100% confidence as I did a small research, not thorough, but I'm pretty sure that this is similar to Kuppe's dataset

**Comment by MightyAx** [comment]
seems fine from this list:
https://api.ingest.archive.data.humancellatlas.org/exportJobs/62b590a2b85bb84636c5f149/entities?status=EXPORTED

edited the export job to have:
`"isDataTransferComplete": true`

**Comment by MightyAx** [comment]
the export has been made correctly, it's just ingest that hasn't been updated to reflect this yet.
Will do so when there is not the r18 deadline

**Comment by MightyAx** [comment]
set as exported and restarted state tracking

**Comment by amnonkhen** [comment]
@MightyAx will set project status to Exported.
