### ISSUE TITLE
Dataset stuck in exporting

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#863]
- [ ] [34da2c5f-8011-48af-a7fd-ad2f56ec10f4](https://contribute.data.humancellatlas.org/projects/detail?uuid=34da2c5f-8011-48af-a7fd-ad2f56ec10f4&tab=upload) wrangling ticket #785
- [x] [fcaa53cd-ba57-4bfe-af9c-eaa958f95c1a](https://contribute.data.humancellatlas.org/projects/detail?uuid=fcaa53cd-ba57-4bfe-af9c-eaa958f95c1a&tab=upload) wrangling ticket #634
- [ ] ~~[1e281905-8dac-4f6d-9e10-f698fb9aa805](https://contribute.data.humancellatlas.org/projects/detail?uuid=1e281905-8dac-4f6d-9e10-f698fb9aa805&tab=project) wrangling ticket #716 - got stuck in exporting in June after an update was made~~
    - This project no longer exists

**Comment by ESapenaVentura** [comment]
For the main purpose of the ticket:

I have taken a look at grafana (Query: `{container=~"ingest-.*"} |= "302c1f08-dc2d-4653-8a43-e8ff5ac5d9f0" |~ "ERROR"`) and it seems like export job with index 73 failed due to a connection error

The number of entities do not match at all for some of the entities (e.g. processes), as showcased below:
```
Staging area 
      8 analysis_file
     10 analysis_protocol
    233 cell_line
    291 cell_suspension
      6 collection_protocol
      2 differentiation_protocol
      4 dissociation_protocol
     12 donor_organism
      4 enrichment_protocol
      4 library_preparation_protocol
    868 process
      1 project
    148 sequence_file
      3 sequencing_protocol
     16 specimen_from_organism

Ingest
"expectedBiomaterials" : 553,
  "expectedProcesses" : 622,
  "expectedFiles" : 156,
  "expectedProtocols" : 31,
  "expectedProjects" : 1,
  "actualLinks" : 5284,
  "expectedLinks" : 5284,
```

So I really don't know what happened here without further investigation.

**Comment by ESapenaVentura** [comment]
Expected vs what there is:

| Entity type | Ingest count | staging area count |
|-----------|--------------|--------------------|
| Biomaterials | 552 | 553 |
| Processes | 622 | 868 |
| Protocols | 31 | 33 | 
| Projects | 1 | 1 |

I really don't know what is happening here. it seems like there were entities deleted and ingest did not acknowledge for them, and new (246???) processes

**Comment by MightyAx** [comment]
Project: [Mapping the developing human immune system across organs](https://contribute.data.humancellatlas.org/projects/detail?uuid=fcaa53cd-ba57-4bfe-af9c-eaa958f95c1a&tab=upload)
Wrangling ticket: #634

This one was just stuck behind a project was is "Actually" stuck, freeing up the export queue and moving just this projects exports across has made this export successfully.

**Comment by MightyAx** [comment]
This ticket shouldn't exist, all of these projects are stuck for different reasons, can wee please just use wrangling tickets in future.
