### ISSUE TITLE
Set up tracking sheet for HCA->SCEA

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#866]
**Goal**

Set up a tracking sheet for HCA -> SCEA

- [x] Fill with existing HCA datasets on SCEA Gitlab (i.e. done and displayed in broswer)
- [x] Fill in "in-progress" or "in review" HCA -> SCEA datasets 
- [ ] Check the tracker sheet with the SCEA team: does it contain all the columns they need?

**Location**

https://docs.google.com/spreadsheets/d/1iQNiES-xLs3wcR6FjKcN9hIXgDFlzpiP2Z6_Syy2QKI/edit#gid=0

**Rationale**

We, and the SCEA team, need to track which HCA datasets have been curated and uploaded to the SCEA Gitlab for display in their browser. For now, a temporary solution is to set up and manage a tracker sheet that we share with them. The long-term goal is integrate SCEA tracking in ingest but this needs to be prioritised in a future sprint/sprints(s). Tagging @gabsie for reference.

**Comment by amnonkhen** [comment]
We should work with a zenhub board for that.

**Comment by ofanobilbao** [comment]
With Ami leaving we might go with Amnon's suggestion and stick to the ZenHub board. So I'll close this ticket. As I believe there is nothing more to do on it
