### ISSUE TITLE
fill_ontologies can't find cell barcode

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#899]
**Description of the problem:**
The script `fill_ontologies` can't find the ontology id for `cell barcode` - and all terms in the [information entity](https://ontology.archive.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000030) branch as well I suspect

When it encounters `cell barcode` it lists a number of terms that have the word cell in them but not cell barcode.
I use the manual input option and input the ontology id EFO:0010198
Then the code breaks with this error:
```
Please input the term manually: EFO:0010208                                                                         
Traceback (most recent call last):
  File "/Users/idazucchi/Documents/script/hca-ebi-wrangler-central/src/fill_ontologies.py", line 328, in <module>
    main(args)
  File "/Users/idazucchi/Documents/script/hca-ebi-wrangler-central/src/fill_ontologies.py", line 322, in main
    parse_wb(args.wb_path, wb, json_schemas, args.zooma, args.keep)
  File "/Users/idazucchi/Documents/script/hca-ebi-wrangler-central/src/fill_ontologies.py", line 292, in parse_wb
    ontology, known_iri = select_term(ontologies_dict, cell.value, programmatic_key,
  File "/Users/idazucchi/Documents/script/hca-ebi-wrangler-central/src/fill_ontologies.py", line 234, in select_term
    return select_term(ontologies_dict, term, key, schema_info, zooma, known_iri)
  File "/Users/idazucchi/Documents/script/hca-ebi-wrangler-central/src/fill_ontologies.py", line 182, in select_term
    first_key = next(iter(ontologies_dict))
TypeError: 'NoneType' object is not iterable
```
**Task**
The script needs to be debugged if this is affecting all wranglers. 
If it's only affecting Ida I will try to figure this one out.

A good place to start would be checking if there is a place where the script checks which ontologies are accepted and make sure it's up to date with the current schema

**Acceptance criteria for the task:**
- [ ] does this issue affect everyone?
- [ ] debug the code
- [ ] script can find the ontology code for `cell barcode` and any other term in the [information entity](https://ontology.archive.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000030) branch

**Comment by ofanobilbao** [comment]
@ESapenaVentura do you know who wrote this script?

**Comment by ESapenaVentura** [comment]
I wrote the script! and marion improved it :) I can take a look if we prioritise it next sprint!

**Comment by idazucchi** [comment]
I've run the script again and it had no issue finding the cell barcode ontology, so I'm not sure of what caused the errors.

I will close the ticket now - it can reopened if the problem comes up again
