### ISSUE TITLE
Error importing submission: DevelopmentalOriginsNeuroblastoma

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#917]
I am getting an error when trying to import a submission (after uploading a metadata spreadsheet) to ingest prod.

# Links
- [project in ingest](https://contribute.data.humancellatlas.org/submissions/detail?uuid=6f1757d3-8019-4e03-9de9-642f12e8a14a&project=c8e6c5d9-fcde-4845-bead-ff96999e3051) DevelopmentalOriginsNeuroblastoma
- dataset ticket: ebi-ait/hca-ebi-wrangler-central#830
- [metadata sheet](https://docs.google.com/spreadsheets/d/1B2gP1FmAXd7smUDULK6Iq4o-I3jrtp0CkoYclTGHoyw/edit#gid=2012972694)
- [errors logs in monitoring](https://monitoring.ingest.archive.data.humancellatlas.org/goto/SA-UXx7Vk)

## Error message:
```
An error occurred importing the file.

Received an HTTP 500 from http://172.20.59.73/projects/60c36c9dac92ec2ecbb54a56/submissionEnvelopes: http://172.20.59.73/projects/60c36c9dac92ec2ecbb54a56/submissionEnvelopesUnexpected server error
```

## Scenario:
1. old project in index w/o submissions
1. create submission - uploaded successfully
1. delete submission - success
1. create a 2nd submission
1. notice error

# Workaround
Use a freshly created project instead of a project that has been around for a long time.

# Tasks:
- [x] figure out how the affected project is different from a new one I created, and what causes it to have the problem. 
- [ ] add a protection against such a scenario
- [x] offer a workaround to Wranglers until code is fixed.

**Comment by amnonkhen** [comment]
@ami add the error you are getting to the ticket.

**Comment by rachadele** [comment]
Also seeing this error with ocularAnteriorSegmentAtlas (uuid b6d361a2-a029-47df-ba8e-ea1d37ecd541)

**Comment by gabsie** [comment]
@amnonkhen will work on this today.

**Comment by amnonkhen** [comment]
I am not able to reproduce this error with a new dataset.
It only happens to the datasets reported in the ticket.
I have not found out a case, and therefor still do not have a fix.

**Comment by amnonkhen** [comment]
I am able to reproduce the problem locally by copying the ingest mongodb to a local instance.
I still do not how the affected project is different from a new one I created, and what cause it to have the problem.

**Comment by amnonkhen** [comment]
Taking a closer look using the debugger, I notice that in Ami's project case the list of linked submissions that is passed to the `ProjectLinkChangeListener` in the `linked` argument contains 2 elements: a null element and the newly created submission.

![image.png](https://images.zenhubusercontent.com/600ed297091d3ea152b83c2d/d605487a-dd9a-4b68-a070-84387dedd33a)

**Comment by amnonkhen** [comment]
Thanks @MightyAx 
I will start by suggesting a workaround to the wranglers, and then add protection in the code against such cases.

**Comment by MightyAx** [comment]
deployed to staging, integration tests failed for a different reasons.
If the integration tests pass we can deploy to production.

**Comment by MightyAx** [comment]
production has been updated with a bug fix for this issue

**Comment by ESapenaVentura** [comment]
Fix worked, moving to done
