### ISSUE TITLE
Cell-to-cell-suspension test data

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#927]
**Description**

Testing experiment design in which a cell suspension is used as input to another cell suspension (both in the "Cell suspension" tab).

E.g.
Mouse cells -> cell suspension 1
Human cells -> cell suspension 2
Mouse cells (cell suspension 1) + Human cells (cell suspension 2) -> cell suspension 3

**Context**
These datasets have cell-to-cell-suspension linking:
#853 - HumanMelanocyteDevelopment
#718 - BenchmarkingSingleCellProtocols
We want to ensure this type of linking is supported by the downstream components

**Task**
We need to generate test data for this scenario and get the DCP's approval.

**PR**
https://github.com/HumanCellAtlas/schema-test-data/pull/28

**Acceptance criteria**
- [x] generate test data --> [spreadsheet](https://docs.google.com/spreadsheets/d/1CQ6e2AiJin5JaDAMfeu5poqDB-9y2wXf0s3AYJeFbiQ/edit#gid=513593862)?
- [x] upload test data to test data repo
- [x] request reviews
- [ ] green light
- [ ] update SOP --> best practices

**Comment by ami-day** [comment]
PR: https://github.com/HumanCellAtlas/schema-test-data/pull/28

**Comment by ami-day** [comment]
Awaiting within team review. Once approved, I will then request external review (dcp2)

**Comment by gabsie** [comment]
add small description on the test data, so that people can understand what they should approve. @ami-day

**Comment by MightyAx** [comment]
[PR](https://github.com/HumanCellAtlas/schema-test-data/pull/28) for review today
@ESapenaVentura @idazucchi

**Comment by idazucchi** [comment]
ami requested reviews from the dcp components

**Comment by amnonkhen** [comment]
Waiting on Hannes to write a test in Azul.

**Comment by idazucchi** [comment]
I've opened a [PR](https://github.com/HumanCellAtlas/schema-test-data/pull/29) for the test data SOP to address some of the issues we came across while working on this ticket

**Comment by Wkt8** [comment]
Reviews made, @idazucchi to merge.

**Comment by idazucchi** [comment]
@ami-day to ping Hannes to get a timeline

**Comment by ofanobilbao** [comment]
@gabsie asked Trevor for a timeline on this on the DCP demo on Tuesday

**Comment by Wkt8** [comment]
Hannes has asked ami for additional info

**Comment by ofanobilbao** [comment]
All that Hannes requested is in the PR. Enrique tried to produce what Hannes required. But encountered issues with Graph validator. Ami (if capacity allows) could manually provide a diagram with experimental design. To follow up this afternoon with Ami and decide on next steps.

**Comment by ESapenaVentura** [comment]
@ESapenaVentura to create graph and show to hannes

**Comment by Wkt8** [comment]
Attempted to run the ingest-graph-validator but there seems to be import errors with the ingest-graph-validator (they are not dataset-specific errors).

**Comment by ESapenaVentura** [comment]
Wrote in the PR - Hopefully with all the info needed

**Comment by ofanobilbao** [comment]
Still waiting for Hannes to respond on the PR

**Comment by ESapenaVentura** [comment]
Daniel Working on tests at the moment

**Comment by ESapenaVentura** [comment]
There was a comment by hannes that I misread about cell counts

I have now answered with the proper modelling

**Comment by ESapenaVentura** [comment]
I need to re-make the test data - Currently [in progress](https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=5880f4fb-b1f0-40e2-8711-bb011be48335&project=33c4efd0-f5cb-416b-ae7c-63f2cf9fa658)

**Comment by ESapenaVentura** [comment]
The process is finished - Asked Hannes to test the new data

**Comment by anu-shiva** [comment]
Daniel to run the test on new data.

**Comment by Wkt8** [comment]
Merged! Now usable for release 25 and onwards.
