### ISSUE TITLE
Curate new nxn projects

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#933]
**Task**
Script run on 7-10-2022
Curate the projects in this ticket following the instructions in the [SOP](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/dataset_acknowledgement_SOP.html#manual-curation-after-addition)
- [x] [Organoid Modeling of the Tumor Immune Microenvironment](https://contribute.data.humancellatlas.org/projects/detail?uuid=d6c7167c-f2b1-43d9-938b-3b485ffda844)
- [x] [Sampling artifacts in single-cell genomics cohort studies](https://contribute.data.humancellatlas.org/projects/detail?uuid=ebb6c3fe-881d-4680-be77-3a37ff29e71d) - deleted! - duplicate of [this](https://contribute.data.humancellatlas.org/projects/detail?uuid=5b328561-4a97-40ac-b7ad-6a90fc59d374), which is already published
- [x] [Transcriptional and Functional Analysis of CD1c+ Human Dendritic Cells Identifies a CD163+ Subset Priming CD8+CD103+ T Cells](https://contribute.data.humancellatlas.org/projects/detail?uuid=b2d7aa64-35c8-422c-a0d6-dd47888117dd)
- [x] [A single-cell atlas of liver metastases of colorectal cancer reveals reprogramming of the tumor microenvironment in response to preoperative chemotherapy](https://contribute.data.humancellatlas.org/projects/detail?uuid=2d9f16b5-a114-4458-877e-fdc90f9a4355)
- [x] [Single-cell transcriptomics reveals a distinct developmental state of KMT2A-rearranged infant B-cell acute lymphoblastic leukemia](https://contribute.data.humancellatlas.org/projects/detail?uuid=4a3f4c80-7fc6-47a4-a8f0-bffa76df9c18) - managed access but no matrices available --> eligible priority 3
- [x] [Organoid-based single-cell spatiotemporal gene expression landscape of human embryonic development and hematopoiesis](https://contribute.data.humancellatlas.org/projects/detail?uuid=f9fb046a-5e74-4ce8-a027-da741aa332c8)
- [x] [Transcriptomic Features in a Single Extracellular Vesicle via Single-Cell RNA Sequencing](https://contribute.data.humancellatlas.org/projects/detail?uuid=7c031176-9b0b-4a18-aeb4-f844f92e776b) - no access to the paper, can I get it through the library?

**Comment by idazucchi** [comment]
I've requested access to the missing paper through the library service

**Comment by idazucchi** [comment]
The last paper looks very interesting but it's probabaly outside of our scope - they sequenced trascripts found in extracellular vescicles of 2 cell lines ( human chronic myeloid leukemia cell line K562 and mesenchymal stem cells MSC)
the accession is [HRA002821](https://ngdc.cncb.ac.cn/gsa-human/browse/HRA002821)

**Comment by idazucchi** [comment]
The last paper looks very interesting but it's probabaly outside of our scope - they sequenced trascripts found in extracellular vescicles of 2 cell lines ( human chronic myeloid leukemia cell line K562 and mesenchymal stem cells MSC)
the accession is [HRA002821](https://ngdc.cncb.ac.cn/gsa-human/browse/HRA002821)
