### ISSUE TITLE
Onboarding tasks for Anu

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#976]
# Tasks

Welcome to the HCA DCP! We are pleased to introduce you to the data wrangling team. Before beginning to work by yourself, you'll be asked to complete a set of tasks and meetings. These will guide you through both the general and specifics of your role, and it will help us make sure you understand how we work in the team. Your introductory tasks are:

- [x] Read the [onboarding document](https://ebi-ait.github.io/hca-ebi-wrangler-central/ebi-wrangler-onboarding.html).
   - [x] Add yourself to the table of wranglers via a PR
- [x] Move this ticket from "to do" to "in progress" Pipeline in ZenHub.
- [x] Create an issue for each [general task](#general-tasks) and link it to this epic.
- [x] Clone all the basic repos to your computer (look at the [onboarding document](https://ebi-ait.github.io/hca-ebi-wrangler-central/ebi-wrangler-onboarding.html) for more information)
- [x] Locate all the documents regarding SOPs. You don't need to read them for now, but make sure to know where they are (Via notes, bookmarking, etc)

## General tasks

These are more wrangling-specific tasks. They will provide you with the basic knowledge necessary to perform your future tasks in the team. These include:
1. Watch HCA Metadata Standard 101 [video](https://drive.google.com/open?id=12hGA3_ARTKl-W0JxMKm8fHqvx31L3Ohf) ([slides](https://drive.google.com/open?id=1CJZfFpVFPolYPf30NSNn3A4CPVHmbfbaHUKlzCqBz_c)).
1. Familiarise yourself with the projects and Standard Operating Procedures (SOPs) inside the [hca-ebi-wrangler-central repository](https://github.com/ebi-ait/hca-ebi-wrangler-central/)
1. Read up on FAIR Data Principles
    - [The FAIR Guiding Principles for scientific data management and stewardship (Wilkinson 2016)](https://www.nature.com/articles/sdata201618)
    - [A design framework and exemplar metrics for FAIRness (Wilkinson 2018)](https://www.nature.com/articles/sdata2018118)
    - [Quick summary](https://www.force11.org/group/fairgroup/fairprinciples) of FAIR Data Principles
    - Also related: [Uniform resolution of compact identifiers for biomedical data (Wimalaratne 2018)](https://www.nature.com/articles/sdata201829)
1. Add or update tickets in wrangling or metadata-schema repo to reflect work being done.
<These tasks are in the order they are meant to be introduced to the wrangler.>

## Specific role tasks

These tasks will give you an insight on your role, and provide you with the appropriate tools to proceed in your job. As your first dataset, you have been assigned to wrangle the publication [Single-Cell RNA Sequencing in Multiple Pathologic Types of Renal Cell Carcinoma Revealed Novel Potential Tumor-Specific Markers](https://doi.org/10.3389/fonc.2021.719564). To familiarise yourself to the wrangling process, your tasks regarding this dataset are:

- [x] Create a ticket in this repository using the `Published project tracker` template - ebi-ait/hca-ebi-wrangler-central#1010
- [x] Read the paper and gather the following information:
   - [x] Type of tissue: primary, cell line, organoid?
   - [x] Technology used for library preparation: 10x, smart-seq2?
   - [x] Developmental stage of the donors: Adult, fetal, embryos?
- [x] Generate a spreadsheet template from the [project page](https://contribute.data.humancellatlas.org/) in ingest. Try to use the information gathered from the previous point to generate it.
- [x] Create a google drive folder inside the [brokering](https://drive.google.com/drive/folders/118kh4wiHmn4Oz9n1-WZueaxm-8XuCMkA) folder and store the spreadsheet there
- [x] Read through the paper and try to fill the spreadsheet with the available information. Use the [spreadsheet quick guide](https://ebi-ait.github.io/hca-metadata-community/contributing/spreadsheet-guide.html) to guide you through the process.
- [x] Once completed, post in the ticket that the dataset is ready for **secondary review** and tag @idazucchi .
- [x] When secondary review is completed, you will have a meeting with @idazucchi  to go through the corrections/queries
- [x] Follow the rest of the items in the ticket you created to finish the submission

# Onboard Meetings

These meetings will help you understand some aspects of the work here, as well as our work policy and important details about what technologies we use. They will be short (around 30 minutes) and you should try to get at least one per day. You will be expected to book the meeting with the person that is supposed to give it.

1. Introduction to the DCP - @gabsie 
1. AIT organisation; team days, overall routine - @gabsie 
1. Introduction to agile: The manifesto and basic concepts. Technical Lead (TL), Product Owner (PO), sprint, tickets and story points. Zenhub walk-through and standup format -  @amnonkhen 
1. Computational environments: DCP's Github workflow, recommended software (PyCharm, sublime, google sync, notes, postman). @ESapenaVentura 
1. Developmental environments: Development, Staging, Production. @amnonkhen  
1. Metadata repository 1: Entities structure: core, type and module. Graphs as a tool to represent a project. @ESapenaVentura 
1. Metadata repository 2: Introduction to JSON, schema evolution and versioning. @ESapenaVentura 
1. Overview of metadata schema updates - @ESapenaVentura 
1. Technologies: 10x, SMART-Seq2, Imaging transcriptomics, CITE-Seq, ATAC-Seq, 10x Visium **TBD**
1. Intro to wrangling for downstream portals @Wkt8 
1. Wrangling repository: Tools, tickets, MarkDown documents and processes. Graph validator. @ESapenaVentura 
1. The spreadsheets and the contributor form. General tour and how to generate one. @ESapenaVentura 
1. Linked knowledge: Quick introduction to ontologies. **TBD**
1. Components: DCP and organisation. @gabsie 
1. Ingest component: Overview of ingest infrastructure.  **Dev TBD**

# Acceptance criteria

- [ ] Finish all the tasks outlined.
- [ ] Close this issue.

**Comment by anu-shiva** [comment]
[Notes] (https://docs.google.com/document/d/1gwF7K6cW3FZywKlgVuP9nVyD4b7CN_IO/edit?usp=share_link&ouid=113226892983117039662&rtpof=true&sd=true)
